document.addEventListener('DOMContentLoaded',()=>{
 const grid=document.getElementById('music-grid');
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
 const directSpotify={"It's You":'https://open.spotify.com/track/2kUpOUbgVDR6DylVP7wYc9',"Don't Say It":'https://open.spotify.com/track/7iFZf3AybscGkT2Mfm7HPY',"Don't Say It (Acoustic)":'https://open.spotify.com/track/3E4nfIVL6b3smwm4h43XPl','Hindsight':'https://open.spotify.com/track/0Pby63EbxsDnJbyhoEgSf9','When The World Gets Loud':'https://open.spotify.com/track/0jPdPyTKpprolooEm2juSL','Light':'https://open.spotify.com/track/0O6aisXk8DD13vYXUdKmOz','My Light':'https://open.spotify.com/track/50KiDJ0VwrcHMdOcoU9pas','Manic Side':'https://open.spotify.com/track/6D4Sk7InAlTptkj2n7IAVZ',"Don't Let Me Go":'https://open.spotify.com/track/5kh3bAT2XMyczJUkXcjdhc','Signal Light Sermon':'https://open.spotify.com/track/0JsYq1b9zJarkdTAbKXPMD','Lost In The Fog':'https://open.spotify.com/track/19S7C7P04jPg4gNsJgu9VX','In The End':'https://open.spotify.com/track/05RKwFFK1GLZO3HRLY1zCJ','Stay Here':'https://open.spotify.com/track/7A83npfB88hyF0Zo1Td5xz'};
 const releaseSpotify={};
 const render=items=>{grid.innerHTML=items.map(s=>{const title=esc(s.trackName),release=esc(s.collectionName||'LIL SYNN'),art=(s.artworkUrl100||'').replace('100x100bb','600x600bb'),apple=s.trackViewUrl||'',spotify=directSpotify[s.trackName]||releaseSpotify[s.trackName]||'',year=s.releaseDate?new Date(s.releaseDate).getFullYear():'';if(!apple&&!spotify)return '';return `<article class="music-card"><a href="${apple||spotify}" target="_blank" rel="noopener noreferrer" aria-label="Open ${title}">${art?`<img src="${art}" alt="${title} — LIL SYNN artwork" loading="lazy" decoding="async">`:'<div class="music-placeholder">LIL SYNN</div>'}</a><div class="music-card-body"><h3 class="music-card-title">${title}</h3><p class="music-card-meta">${release}${year?' · '+year:''}</p><div class="music-card-links">${spotify?`<a href="${spotify}" target="_blank" rel="noopener noreferrer" aria-label="Open ${title} on Spotify">SPOTIFY</a>`:''}${apple?`<a href="${apple}" target="_blank" rel="noopener noreferrer" aria-label="Open ${title} on Apple Music">APPLE</a>`:''}</div></div></article>`}).join('')};
 (async()=>{if(!grid)return;try{
   const [appleResponse,catalogResponse]=await Promise.all([
     fetch('https://itunes.apple.com/lookup?id=1850720041&entity=song&limit=200',{cache:'no-store'}),
     fetch('/release-catalog.json',{cache:'no-store'})
   ]);
   if(!appleResponse.ok)throw Error('Apple catalog unavailable');
   const appleData=await appleResponse.json();
   const songs=(appleData.results||[]).filter(x=>x.wrapperType==='track'&&x.kind==='song'&&x.artistName==='LIL SYNN'&&x.trackName).filter((x,i,a)=>a.findIndex(y=>y.trackId===x.trackId)===i);
   if(catalogResponse.ok){const catalog=await catalogResponse.json();Object.assign(releaseSpotify,catalog.trackSpotify||{});}
   if(!songs.length)throw Error('No LIL SYNN songs found');
   // Shuffle the complete catalog, then prefer different releases so one page load
   // is not dominated by the same album/EP. The final order is shuffled again.
   const randomized=shuffle(songs);const chosen=[];const releases=new Set();
   for(const song of randomized){if(chosen.length>=8)break;const release=song.collectionName||'';if(!releases.has(release)){chosen.push(song);releases.add(release)}}
   if(chosen.length<8){for(const song of randomized){if(chosen.length>=8)break;if(!chosen.some(x=>x.trackId===song.trackId))chosen.push(song)}}
   render(shuffle(chosen));
 }catch(e){console.warn('Random LIL SYNN music unavailable; existing catalog remains.',e)}})();
 const about=document.querySelector('#about .about-card .mt-7');if(about&&!about.querySelector('[data-tidal-profile]')){const a=document.createElement('a');a.href='https://tidal.com/artist/69300200';a.target='_blank';a.rel='noopener noreferrer';a.className='cta-secondary';a.dataset.tidalProfile='true';a.textContent='TIDAL PROFILE';about.appendChild(a)}
 const legal=document.querySelector('footer nav[aria-label="Legal navigation"]');if(legal&&!document.querySelector('[data-social-icon-row]')){const row=document.createElement('div');row.dataset.socialIconRow='true';row.className='mt-5 mb-16 flex flex-wrap justify-center items-center gap-4';const socials=[['youtube','https://www.youtube.com/@LILSYNNOFFICIAL'],['spotify','https://open.spotify.com/artist/6ozcOAnRAUPn3z5c0GR5kU'],['apple-music','https://music.apple.com/us/artist/lil-synn/1850720041'],['instagram','https://www.instagram.com/lilsynnofficial/'],['twitter','https://x.com/lilsynnofficial'],['soundcloud','https://soundcloud.com/lilsynnofficial'],['tiktok','https://www.tiktok.com/@lilsynnofficial'],['facebook','https://www.facebook.com/lilsynnofficial']];row.innerHTML=socials.map(([n,u])=>`<a href="${u}" target="_blank" rel="noopener noreferrer" aria-label="${n}" class="inline-flex items-center justify-center w-11 h-11 rounded-full border border-[#ff008f]/40 bg-black/70 hover:border-[#ff4fd8] hover:scale-105 transition-transform"><img src="assets/images/icons/${n}.svg" alt="" aria-hidden="true" class="w-6 h-6 object-contain"></a>`).join('');legal.parentNode.insertBefore(row,legal)}
 const videoGrid=document.getElementById('youtube-grid');if(videoGrid&&!videoGrid.dataset.fallbackEnhanced){videoGrid.dataset.fallbackEnhanced='true';const addFallback=async()=>{try{const api=await fetch('/api/youtube',{cache:'no-store'});if(api.ok){const apiData=await api.json();if(apiData?.items?.length)return}const r=await fetch('/assets/youtube-fallback.json',{cache:'no-store'});if(!r.ok)return;const d=await r.json();if(videoGrid.querySelectorAll('article').length!==6)return;(d.items||[]).slice(6,8).forEach(item=>{const vid=item.videoId||item.id?.videoId;if(!vid)return;const title=esc(item.snippet?.title||'LIL SYNN Video');const card=document.createElement('article');card.className='glass rounded-3xl overflow-hidden border border-[#ff008f]/30 hover:border-[#ff4fd8]';card.innerHTML=`<div style="position:relative;aspect-ratio:16/9;background:#000;overflow:hidden"><a href="https://www.youtube.com/watch?v=${encodeURIComponent(vid)}" target="_blank" rel="noopener noreferrer"><img src="https://i.ytimg.com/vi/${encodeURIComponent(vid)}/hqdefault.jpg" alt="${title}" style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover" loading="lazy"></a></div><div class="p-4 text-sm font-['Rajdhani'] text-center">${title}</div>`;videoGrid.appendChild(card)})}catch{}};new MutationObserver(()=>{if(videoGrid.querySelectorAll('article').length===6)addFallback()}).observe(videoGrid,{childList:true,subtree:true});setTimeout(addFallback,3000)}
});
