if(!window.__lsSiteMotionLoaded){window.__lsSiteMotionLoaded=true;
(()=>{
const ensureBackgroundVideo=()=>{
  let video=document.getElementById('bgVideo');
  if(!video){video=document.createElement('video');video.id='bgVideo';document.body.prepend(video)}else if(video.parentElement!==document.body){document.body.prepend(video)}
  video.className='ls-global-bg-video';video.setAttribute('aria-hidden','true');video.autoplay=true;video.muted=true;video.playsInline=true;video.loop=true;video.preload='metadata';
  let overlay=document.querySelector('.ls-global-bg-overlay');
  if(!overlay){overlay=document.createElement('div');overlay.className='ls-global-bg-overlay';document.body.prepend(overlay)}
  if(video.querySelector('source')){video.play().catch(()=>{});return}
  const attach=()=>{if(video.querySelector('source'))return;const source=document.createElement('source');source.src='/assets/mov/LG_BG_STARS.webm';source.type='video/webm';video.appendChild(source);video.load();video.play().catch(()=>{})};
  if('requestIdleCallback' in window)requestIdleCallback(attach,{timeout:700});else setTimeout(attach,250);
};
const addHomepageRandomize=()=>{const grid=document.getElementById('music-grid');if(!grid)return;const buttons=[...document.querySelectorAll('.discover-button')];if(buttons.length>1)buttons.slice(1).forEach(b=>b.closest('.homepage-refinement')?.remove());if(document.querySelector('.discover-button'))return;const panel=document.createElement('div');panel.className='homepage-refinement';panel.innerHTML='<button type="button" class="discover-button">RANDOMIZE</button>';grid.parentNode.insertBefore(panel,grid);panel.querySelector('button').addEventListener('click',()=>window.lilSynnRefreshMusic?.())};
const rhythm=()=>{if(document.getElementById('homepage-rhythm-final'))return;const style=document.createElement('style');style.id='homepage-rhythm-final';style.textContent=`#home,#contact{background:rgba(128,128,128,.18)!important}#presave,#music,#videos,#about,#merch,#signal{background:rgba(8,8,8,.62)!important;border-top:0!important;border-bottom:0!important;box-shadow:none!important;outline:0!important}#presave::before,#presave::after,#music::before,#music::after,#videos::before,#videos::after,#about::before,#about::after,#merch::before,#merch::after,#signal::before,#signal::after{border:0!important;box-shadow:none!important;background:transparent!important}#presave + #music,#music + #videos,#videos + #about,#about + #merch,#merch + #signal{border-top:0!important}`;document.head.appendChild(style)};
const init=()=>{ensureBackgroundVideo();addHomepageRandomize();rhythm()};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
}

/* LIL SYNN global visual/release corrections */
(()=>{
const norm=v=>String(v??'').toLowerCase().normalize('NFKD').replace(/[’']/g,'').replace(/[^a-z0-9]+/g,'');
const singleArt={'neverknown':'Never Known_album_cover.jpg','homeacousticversion':'home_acoustic_version.png','ididitagain':'I DID IT AGAIN.jpg','rescueyouacousticversion':'RESCUE_YOU_A.png','somewhereinbetween':'somewhere_in_between.jpg','blackglass':'23_lil_synn_black_glass.jpg','blackglassacousticversion':'24_lil_synn_black_glass___acoustic_version.jpg','staticonmytongue':'25_lil_synn_static_on_my_tongue.jpg','itsinhereyes':'26_lil_synn_it_s_in_her_eyes.jpg','fadeintoyou':'1_lil_synn_fade_into_you.jpg','lover':'27_lil_synn_lover.jpg','everytime':'28_lil_synn_every_time.jpg','rescueyou':'29_lil_synn_rescue_you.jpg','heal':'30_lil_synn_heal.jpg','backfromtheblackout':'31_lil_synn_back_from_the_blackout.jpg','burnitdown':'32_lil_synn_burn_it_down.jpg','hindsight':'33_lil_synn_hindsight.jpg','whentheworldgetsloud':'34_lil_synn_when_the_world_gets_loud.jpg','light':'35_lil_synn_light.jpg','manicside':'36_lil_synn_manic_side.jpg','dontsayitacoustic':'37_lil_synn_don_t_say_it___acoustic.jpg','dontsayit':'38_lil_synn_don_t_say_it.jpg','signallightsermon':'39_lil_synn_signal_light_sermon___remastered_2026.jpg','lostinthefog':'40_lil_synn_lost_in_the_fog.jpg','intheend':'41_lil_synn_in_the_end.jpg','stayhere':'42_lil_synn_stay_here.jpg','home':'43_lil_synn_home.jpg','mylight':'44_lil_synn_my_light.jpg','tiesremain':'45_lil_synn_ties_remain.jpg','gravityandghosts':'46_lil_synn_gravity_and_ghosts.jpg','wordtoword':'47_lil_synn_word_to_word.jpg','shattered':'48_lil_synn_shattered.jpg','mirrors':'49_lil_synn_mirrors.jpg','faith':'50_lil_synn_faith.jpg','throughtheflames':'51_lil_synn_through_the_flames.jpg','wounds':'52_lil_synn_wounds.jpg','discernment':'53_lil_synn_discernment.jpg','dontletmego':'54_lil_synn_dont_let_me_go.jpg','ifustayded':'55_lil_synn_if_u_stay_ded.jpg','alreadyfamous':'56_lil_synn_already_famous.jpg','somewhereinbetween':'57_lil_synn_somewhere_in_between.jpg'};
const artFor=title=>{const src=singleArt[norm(title)];return src?'/assets/images/icons/album_art/'+encodeURIComponent(src):''};
const prepareSingleArt=single=>{if(single.querySelector('.single-art'))return;const h=single.querySelector('h2');if(!h)return;const src=artFor(h.textContent.trim());if(!src)return;const img=document.createElement('img');img.className='single-art';img.src=src;img.alt=h.textContent.trim()+' artwork';img.loading='lazy';img.decoding='async';h.insertAdjacentElement('beforebegin',img)};
const reorderReleases=async()=>{const root=document.querySelector('.release-page #releases');if(!root)return;const singles=[...root.querySelectorAll('.singles .single')];const collections=[...root.querySelectorAll('.collection')];if(!singles.length&&!collections.length)return;let catalog;try{catalog=await fetch('/release-catalog.json',{cache:'no-store'}).then(r=>r.json())}catch{return}const order=Array.isArray(catalog.order)?catalog.order:[];const key=v=>norm(v);const collectionMap=new Map(collections.map(x=>[key(x.querySelector('.name')?.textContent),x]));const singleMap=new Map(singles.map(x=>[key(x.querySelector('h2')?.textContent),x]));root.innerHTML='';root.classList.add('release-mixed');for(const title of order){const k=key(title),collection=collectionMap.get(k),single=singleMap.get(k);if(collection)root.appendChild(collection);else if(single){prepareSingleArt(single);root.appendChild(single)}}for(const collection of collections)if(!collection.isConnected)root.appendChild(collection);for(const single of singles)if(!single.isConnected){prepareSingleArt(single);root.appendChild(single)}root.dataset.mixedReady='1'};
const releaseFix=()=>{const root=document.querySelector('.release-page #releases');if(!root)return;const observer=new MutationObserver(()=>{if(root.dataset.mixing)return;root.dataset.mixing='1';root.dataset.mixedReady='';reorderReleases().finally(()=>{root.dataset.mixing=''})});observer.observe(root,{childList:true});reorderReleases()};
const videoOrder=()=>{const grid=document.getElementById('youtube-grid');if(!grid||grid.dataset.orderObserver)return;grid.dataset.orderObserver='1';const fix=()=>{const cards=[...grid.children].filter(x=>x.matches('article'));if(cards.length<2)return;const seenIds=new Set(),seenTitles=new Set();cards.forEach(card=>{const id=card.querySelector('[data-video-id]')?.getAttribute('data-video-id')||'',title=norm(card.querySelector('[data-video-title]')?.getAttribute('data-video-title')||card.textContent||'');if(seenIds.has(id)||seenTitles.has(title))card.remove();else{seenIds.add(id);if(title)seenTitles.add(title)}});const remaining=[...grid.children].filter(x=>x.matches('article'));if(remaining.length<2)return;fetch('/release-catalog.json',{cache:'no-store'}).then(r=>r.json()).then(c=>{const order=(c.order||[]).map(norm);remaining.sort((a,b)=>{const at=norm(a.querySelector('[data-video-title]')?.getAttribute('data-video-title')||a.textContent||''),bt=norm(b.querySelector('[data-video-title]')?.getAttribute('data-video-title')||b.textContent||'');const ai=order.indexOf(at),bi=order.indexOf(bt);return(ai<0?9999:ai)-(bi<0?9999:bi)}).forEach(c=>grid.appendChild(c))}).catch(()=>{})};new MutationObserver(fix).observe(grid,{childList:true});fix()};
const init=()=>{releaseFix();videoOrder()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();