/* LIL SYNN conversion, discovery, and instrumentation polish */
(()=>{
const norm=v=>String(v??'').toLowerCase().normalize('NFKD').replace(/[’']/g,'').replace(/[^a-z0-9]+/g,'');
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const emit=(name,detail={})=>{document.dispatchEvent(new CustomEvent('lilsynn:analytics',{detail:{name,...detail,path:location.pathname,timestamp:Date.now()}}));const endpoint=window.LS_ANALYTICS_ENDPOINT;if(endpoint&&/^https:\/\//.test(endpoint)){try{navigator.sendBeacon(endpoint,JSON.stringify({name,...detail,path:location.pathname,timestamp:Date.now()}))}catch{}}};
const wireEvents=()=>{document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;const text=(a.textContent||'').trim().toUpperCase();if(/SPOTIFY|APPLE MUSIC|YOUTUBE/.test(text))emit('stream_click',{platform:text,href:a.href});else if(/OPEN RELEASE|LISTEN NOW|LISTEN/.test(text))emit('listen_click',{label:text,href:a.href});else if(/ORACLE/.test(text))emit('oracle_click',{href:a.href});});};
const currentFrequency=()=>{if(location.pathname!=='/'&&location.pathname!=='/index.html')return;const target=document.querySelector('#presave');if(!target||target.querySelector('[data-ls-current-frequency]'))return;fetch('/release-catalog.json',{cache:'default'}).then(r=>r.ok?r.json():null).then(c=>{const title=c?.order?.[0];if(!title)return;const g=c.groups?.[title];const type=(g?.type||'SINGLE').toUpperCase();const card=document.createElement('section');card.className='ls-current-frequency';card.dataset.lsCurrentFrequency='true';card.innerHTML=`<div><span class="ls-current-kicker">● CURRENT FREQUENCY</span><h2>${esc(title)}</h2><p>${esc(type)} · THE LATEST SIGNAL</p></div><a class="cta-primary" href="/release.html?id=${encodeURIComponent(title)}">ENTER FREQUENCY</a>`;target.parentNode.insertBefore(card,target);};}).catch(()=>{});};
const tiktokEntry=()=>{if(localStorage.getItem('lsTikTokEntryDismissed')==='1')return;const q=new URLSearchParams(location.search);const fromTikTok=q.get('from')?.toLowerCase()==='tiktok'||/tiktok\.com$/i.test(document.referrer||'')||/tiktok\.com/i.test(location.href);if(!fromTikTok)return;if(document.querySelector('[data-ls-tiktok-entry]'))return;const box=document.createElement('aside');box.className='ls-tiktok-entry';box.dataset.lsTiktokEntry='true';box.innerHTML='<button class="ls-tiktok-close" type="button" aria-label="Close">×</button><span class="ls-current-kicker">SIGNAL RECEIVED</span><h2>YOU FOUND LIL SYNN</h2><p>Music, visuals, and the world behind the signal.</p><div class="ls-tiktok-actions"><a class="cta-primary" href="#music">LISTEN</a><a class="cta-secondary" href="/universe.html">ENTER THE UNIVERSE</a></div>';document.body.appendChild(box);box.querySelector('.ls-tiktok-close').onclick=()=>{localStorage.setItem('lsTikTokEntryDismissed','1');box.remove()};emit('tiktok_entry',{source:'tiktok'});};
const style=()=>{if(document.getElementById('ls-polish-style'))return;const s=document.createElement('style');s.id='ls-polish-style';s.textContent='.ls-current-frequency{display:flex;align-items:center;justify-content:space-between;gap:20px;margin:18px auto 28px;max-width:1180px;padding:18px 20px;border:1px solid rgba(255,0,143,.28);border-radius:18px;background:rgba(5,5,8,.58);box-shadow:0 12px 40px rgba(0,0,0,.22)}.ls-current-frequency h2{margin:.2rem 0 .1rem;font:700 clamp(1.3rem,3vw,2rem) Orbitron,sans-serif;color:#fff}.ls-current-frequency p{margin:0;color:#aaa;font:600 .85rem Rajdhani,sans-serif;letter-spacing:.12em}.ls-current-kicker{display:block;color:var(--ls-glow);font:700 .7rem Rajdhani,sans-serif;letter-spacing:.18em}.ls-tiktok-entry{position:fixed;left:16px;right:16px;bottom:18px;z-index:1900;max-width:520px;margin:auto;padding:22px 24px;border:1px solid rgba(255,79,216,.42);border-radius:20px;background:rgba(5,5,8,.9);backdrop-filter:blur(16px);box-shadow:0 20px 70px rgba(0,0,0,.55)}.ls-tiktok-entry h2{margin:.35rem 0 .3rem;font:700 clamp(1.45rem,6vw,2.1rem) Orbitron,sans-serif;color:#fff}.ls-tiktok-entry p{margin:0 0 16px;color:#bbb;font:1rem/1.4 Rajdhani,sans-serif}.ls-tiktok-actions{display:flex;flex-wrap:wrap;gap:9px}.ls-tiktok-close{position:absolute;right:10px;top:8px;border:0;background:transparent;color:#aaa;font-size:25px;cursor:pointer}.ls-tiktok-close:hover,.ls-tiktok-close:focus-visible{color:var(--ls-glow)}@media(max-width:640px){.ls-current-frequency{margin-left:12px;margin-right:12px;align-items:flex-start;flex-direction:column}.ls-current-frequency .cta-primary{width:100%;text-align:center}.ls-tiktok-entry{bottom:10px;padding:20px}.ls-tiktok-actions a{flex:1 1 100%;text-align:center}}';document.head.appendChild(s)};
const init=()=>{style();wireEvents();currentFrequency();tiktokEntry();};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
