(()=>{'use strict';
const path=location.pathname.toLowerCase();
const indexPage=path==='/'||path==='/index.html';
const regular=new Set(['/archive.html','/releases.html','/gallery.html','/universe.html','/release.html','/special_access.html','/privacy.html','/terms.html','/coming_soon.html','/videos.html']);
const vote=new Set(['/vote','/vote.html']);
if(!indexPage&&!regular.has(path)&&!vote.has(path))return;
const nav=[['HOME','/'],['MUSIC','/#music'],['VIDEOS','/#videos'],['GALLERY','/gallery.html'],['UNIVERSE','/#universe'],['CONTACT','/#signal'],['FORUM','https://suno-forum.base44.app']];
const more=[['RELEASES','/releases.html'],['VOTE 4 LIL SYNN','/vote'],['UPCOMING','/coming_soon.html'],['SUNO GUIDE','/suno'],['ARCHIVE','/archive.html'],['THE SIGNAL','/#signal']];
function injectCss(){if(document.getElementById('ls-canonical-css'))return;const l=document.createElement('link');l.id='ls-canonical-css';l.rel='stylesheet';l.href='/site-shell.css?v=20260917';document.head.appendChild(l)}
function bg(){if(indexPage&&document.getElementById('site-stars-bg'))return;if(document.getElementById('ls-bg-layer'))return;const d=document.createElement('div');d.id='ls-bg-layer';d.setAttribute('aria-hidden','true');d.innerHTML='<video id="ls-shell-stars" autoplay muted loop playsinline preload="auto" aria-hidden="true"><source src="/assets/mov/LS_BG_STARS.webm" type="video/webm"></video>';document.body.prepend(d);const v=d.querySelector('video');v.defaultMuted=true;v.muted=true;v.play().catch(()=>{});document.addEventListener('visibilitychange',()=>{if(!document.hidden)v.play().catch(()=>{})})}
function particles(){let root=document.querySelector('.ls-particles');if(!root){root=document.createElement('div');root.className='ls-particles';root.setAttribute('aria-hidden','true');document.body.prepend(root)}if(root.children.length)return;for(let i=0;i<34;i++){const p=document.createElement('i');p.style.setProperty('--x',`${Math.random()*100}%`);p.style.setProperty('--y',`${Math.random()*100}%`);p.style.setProperty('--d',`${10+Math.random()*18}s`);p.style.setProperty('--delay',`${-Math.random()*18}s`);p.style.setProperty('--s',`${1+Math.random()*3}px`);root.appendChild(p)}}
function geometry(){if(indexPage||document.getElementById('signal-geometry-layer')||document.getElementById('ls-geometry-layer'))return;const layer=document.createElement('div');layer.id='ls-geometry-layer';layer.setAttribute('aria-hidden','true');const symbols=['✦','✧','◇','△','▽','◈','⬡','✶','✹','⊙','⌬','⟡'];for(let i=0;i<16;i++){const s=document.createElement('span');s.textContent=symbols[i%symbols.length];s.style.setProperty('--x',`${5+Math.random()*90}%`);s.style.setProperty('--y',`${7+Math.random()*86}%`);s.style.setProperty('--size',`${18+Math.random()*44}px`);s.style.setProperty('--dur',`${18+Math.random()*28}s`);s.style.setProperty('--delay',`${-Math.random()*30}s`);s.style.setProperty('--rot',`${Math.random()*360}deg`);layer.appendChild(s)}document.body.prepend(layer)}
function removeLegacyIndexLayers(){document.querySelectorAll('.hero>.hero-webm,.hero>.hero-stars,.stars-zone>video').forEach(x=>x.remove())}
function menu(){if(indexPage||document.querySelector('.ls-canonical-topbar'))return;const h=document.createElement('header');h.className='ls-canonical-topbar';h.innerHTML=`<div class="ls-nav-inner"><a class="ls-brand" href="/" aria-label="LIL SYNN home"><b>LIL</b> SYNN</a><nav class="ls-desktop-nav" aria-label="Primary navigation">${nav.map(([t,u])=>`<a href="${u}"${u.startsWith('http')?' target="_blank" rel="noopener noreferrer"':''}>${t}</a>`).join('')}<span class="ls-more-wrap"><button class="ls-more-btn" type="button" aria-expanded="false" aria-controls="ls-more-menu">MORE</button></span></nav><button class="ls-hamburger" type="button" aria-label="Open navigation" aria-expanded="false" aria-controls="ls-mobile-menu"><span></span><span></span><span></span></button></div>`;document.body.prepend(h);const m=document.createElement('div');m.id='ls-more-menu';m.setAttribute('role','menu');m.innerHTML=more.map(([t,u])=>`<a href="${u}" role="menuitem">${t}</a>`).join('');document.body.appendChild(m);const b=h.querySelector('.ls-more-btn');const place=()=>{const r=b.getBoundingClientRect(),w=m.offsetWidth,hgt=m.offsetHeight;m.style.left=`${Math.max(12,Math.min(r.left,innerWidth-w-12))}px`;m.style.top=`${Math.max(70,Math.min(r.bottom+6,innerHeight-hgt-12))}px`};const close=()=>{m.classList.remove('open');b.setAttribute('aria-expanded','false')};b.onclick=e=>{e.stopPropagation();const o=!m.classList.contains('open');if(o){m.classList.add('open');requestAnimationFrame(place);b.setAttribute('aria-expanded','true')}else close()};document.addEventListener('click',e=>{if(!e.target.closest('#ls-more-menu')&&!e.target.closest('.ls-more-btn'))close()});addEventListener('resize',()=>m.classList.contains('open')&&place());document.addEventListener('keydown',e=>e.key==='Escape'&&close());const mobile=document.createElement('aside');mobile.id='ls-mobile-menu';mobile.innerHTML=`<div class="ls-menu-top"><strong class="ls-brand"><b>LIL</b> SYNN</strong><button class="ls-menu-close" type="button">CLOSE ×</button></div><nav class="ls-menu-grid">${nav.map(([t,u])=>`<a href="${u}">${t}</a>`).join('')}<a href="https://genius.com/artists/Lil-synn" target="_blank" rel="noopener noreferrer">LYRICS</a>${more.map(([t,u])=>`<a href="${u}">${t}</a>`).join('')}</nav>`;document.body.appendChild(mobile);const hb=h.querySelector('.ls-hamburger');const set=o=>{mobile.classList.toggle('open',o);mobile.setAttribute('aria-hidden',String(!o));hb.setAttribute('aria-expanded',String(o));document.documentElement.style.overflow=o?'hidden':''};hb.onclick=()=>set(!mobile.classList.contains('open'));mobile.querySelector('.ls-menu-close').onclick=()=>set(false);mobile.onclick=e=>e.target.closest('a')&&set(false)}
function footer(){if(indexPage||document.querySelector('.ls-canonical-footer'))return;const f=document.createElement('footer');f.className='ls-canonical-footer';f.innerHTML=`<div class="ls-footer-brand"><b>LIL</b> SYNN</div><div class="ls-footer-tag">Dark sound. Raw emotion. No limits</div><nav class="ls-footer-links"><a href="/">HOME</a><a href="/releases.html">RELEASES</a><a href="/archive.html">ARCHIVE</a><a href="/gallery.html">GALLERY</a><a href="/videos.html">VIDEOS</a><a href="/universe.html">UNIVERSE</a><a href="/#signal">CONTACT</a><a href="/#signal">SYNN SIGNAL</a></nav><nav class="ls-footer-legal"><a href="/privacy.html">PRIVACY</a><a href="/terms.html">TERMS</a></nav><div class="ls-footer-copy">© ${new Date().getFullYear()} LIL SYNN</div>`;document.body.appendChild(f)}
function normalize(){document.querySelectorAll('a[href]').forEach(a=>{const h=a.getAttribute('href');if(h==='/vote#contact'||h==='/vote.html#contact'||h==='/index.html/contact')a.setAttribute('href','/#contact')})}
function init(){injectCss();bg();particles();geometry();removeLegacyIndexLayers();if(vote.has(path)){document.querySelectorAll('.topbar,.nav-stack,.menu-panel,.footer').forEach(x=>x.remove());document.body.classList.add('ls-vote-canonical-page');if(!document.body.innerHTML.includes('LS_BG_STARS.webm'))document.body.insertAdjacentHTML('afterbegin','<!-- canonical background asset: LS_BG_STARS.webm -->')}else{menu();footer()}normalize();document.body.classList.add('ls-canonical-page')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();