(()=>{'use strict';
const regular=new Set(['/archive.html','/releases.html','/gallery.html','/universe.html','/release.html','/special_access.html','/privacy.html','/terms.html','/coming_soon.html','/videos.html']);
const backgroundOnly=new Set(['/vote','/vote.html']);
const indexPage=location.pathname.toLowerCase()==='/'||location.pathname.toLowerCase()==='/index.html';
const path=location.pathname.toLowerCase();
if(!indexPage&&!regular.has(path)&&!backgroundOnly.has(path))return;
const nav=[['HOME','/'],['MUSIC','/#music'],['VIDEOS','/#videos'],['GALLERY','/gallery.html'],['UNIVERSE','/#universe'],['CONTACT','/#contact'],['FORUM','https://suno-forum.base44.app']];
const more=[['RELEASES','/releases.html'],['VOTE 4 LIL SYNN','/vote'],['UPCOMING','/coming_soon.html'],['SUNO GUIDE','/suno'],['ARCHIVE','/archive.html'],['THE SIGNAL','/#signal']];
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function injectCss(){if(document.getElementById('ls-canonical-css'))return;const l=document.createElement('link');l.id='ls-canonical-css';l.rel='stylesheet';l.href='/site-shell.css?v=20260917';document.head.appendChild(l)}
function bg(){if(document.getElementById('ls-bg-layer'))return;const d=document.createElement('div');d.id='ls-bg-layer';d.setAttribute('aria-hidden','true');d.innerHTML='<video autoplay muted loop playsinline preload="auto"><source src="/assets/mov/LS_BG_STARS.webm" type="video/webm"></video>';document.body.prepend(d);const v=d.querySelector('video');v.defaultMuted=true;v.muted=true;v.play().catch(()=>{});document.addEventListener('visibilitychange',()=>{if(!document.hidden)v.play().catch(()=>{})})}
function geometry(){if(document.getElementById('ls-geometry-layer'))return;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.id='ls-geometry-layer';svg.setAttribute('aria-hidden','true');svg.setAttribute('focusable','false');svg.setAttribute('viewBox','0 0 100 100');svg.setAttribute('preserveAspectRatio','none');const colors=['#ff008f','#ff4fd8','#8b5cf6','#22d3ee','#facc15','#1db954'];const g=document.createElementNS('http://www.w3.org/2000/svg','g');const rnd=(a,b)=>a+Math.random()*(b-a);for(let i=0;i<12;i++){const x=rnd(5,95),y=rnd(5,95),r=rnd(4,17),c=colors[Math.floor(Math.random()*colors.length)],o=rnd(.055,.13);if(i%4===0){const p=document.createElementNS('http://www.w3.org/2000/svg','circle');p.setAttribute('cx',x);p.setAttribute('cy',y);p.setAttribute('r',r);p.setAttribute('fill','none');p.setAttribute('stroke',c);p.setAttribute('stroke-width','.22');p.setAttribute('opacity',o);g.appendChild(p)}else if(i%4===1){const q=document.createElementNS('http://www.w3.org/2000/svg','g');for(let j=0;j<6;j++){const p=document.createElementNS('http://www.w3.org/2000/svg','circle');p.setAttribute('cx',x+Math.cos(j*Math.PI/3)*r*.55);p.setAttribute('cy',y+Math.sin(j*Math.PI/3)*r*.55);p.setAttribute('r',r*.55);p.setAttribute('fill','none');p.setAttribute('stroke',c);p.setAttribute('stroke-width','.16');p.setAttribute('opacity',o);q.appendChild(p)}g.appendChild(q)}else{const p=document.createElementNS('http://www.w3.org/2000/svg','polygon');const n=i%3===0?3:6;let pts='';for(let j=0;j<n;j++){const a=j*2*Math.PI/n-Math.PI/2;pts+=`${x+Math.cos(a)*r},${y+Math.sin(a)*r} `}p.setAttribute('points',pts);p.setAttribute('fill','none');p.setAttribute('stroke',c);p.setAttribute('stroke-width','.2');p.setAttribute('opacity',o);g.appendChild(p)}}svg.appendChild(g);document.body.prepend(svg)}
function removeVoteShell(){if(!backgroundOnly.has(path))return;document.querySelectorAll('.topbar,.nav-stack,.menu-panel,.footer').forEach(el=>el.remove());document.body.classList.add('ls-vote-canonical-page')}
function menu(){if(indexPage||document.querySelector('.ls-canonical-topbar'))return;const h=document.createElement('header');h.className='ls-canonical-topbar';h.innerHTML=`<div class="ls-nav-inner"><a class="ls-brand" href="/" aria-label="LIL SYNN home"><b>LIL</b> SYNN</a><nav class="ls-desktop-nav" aria-label="Primary navigation">${nav.map(([t,u])=>`<a href="${u}"${u.startsWith('http')?' target="_blank" rel="noopener noreferrer"':''}>${t}</a>`).join('')}<span class="ls-more-wrap"><button class="ls-more-btn" type="button" aria-expanded="false" aria-controls="ls-more-menu">MORE</button></span></nav><button class="ls-hamburger" type="button" aria-label="Open navigation" aria-expanded="false" aria-controls="ls-mobile-menu"><span></span><span></span><span></span></button></div>`;document.body.prepend(h);
const moreMenu=document.createElement('div');moreMenu.id='ls-more-menu';moreMenu.setAttribute('role','menu');moreMenu.innerHTML=more.map(([t,u])=>`<a href="${u}" role="menuitem"${u.startsWith('http')?' target="_blank" rel="noopener noreferrer"':''}>${t}</a>`).join('');document.body.appendChild(moreMenu);const moreBtn=h.querySelector('.ls-more-btn');
const placeMore=()=>{const r=moreBtn.getBoundingClientRect();const hgt=moreMenu.offsetHeight;moreMenu.style.top=`${Math.min(window.innerHeight-12-hgt,Math.max(70,r.bottom+6))}px`;moreMenu.style.left=`${Math.min(window.innerWidth-12-moreMenu.offsetWidth,Math.max(12,r.left))}px`};
const closeMore=()=>{moreMenu.classList.remove('open');moreBtn.setAttribute('aria-expanded','false')};moreBtn.addEventListener('click',e=>{e.stopPropagation();const open=!moreMenu.classList.contains('open');if(open){moreMenu.classList.add('open');moreBtn.setAttribute('aria-expanded','true');requestAnimationFrame(placeMore)}else closeMore()});document.addEventListener('click',e=>{if(!e.target.closest('#ls-more-menu')&&!e.target.closest('.ls-more-btn'))closeMore()});window.addEventListener('resize',()=>{if(moreMenu.classList.contains('open'))placeMore()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMore()});
const mobile=document.createElement('aside');mobile.id='ls-mobile-menu';mobile.setAttribute('aria-hidden','true');mobile.innerHTML=`<div class="ls-menu-top"><strong class="ls-brand"><b>LIL</b> SYNN</strong><button class="ls-menu-close" type="button">CLOSE ×</button></div><nav class="ls-menu-grid" aria-label="Mobile navigation">${nav.map(([t,u])=>`<a href="${u}"${u.startsWith('http')?' target="_blank" rel="noopener noreferrer"':''}>${t}</a>`).join('')}<a href="https://genius.com/artists/Lil-synn" target="_blank" rel="noopener noreferrer">LYRICS</a>${more.map(([t,u])=>`<a href="${u}">${t}</a>`).join('')}</nav>`;document.body.appendChild(mobile);const hb=h.querySelector('.ls-hamburger'),mc=mobile.querySelector('.ls-menu-close'),setOpen=o=>{mobile.classList.toggle('open',o);mobile.setAttribute('aria-hidden',String(!o));hb.setAttribute('aria-expanded',String(o));hb.setAttribute('aria-label',o?'Close navigation':'Open navigation');document.documentElement.style.overflow=o?'hidden':''};hb.addEventListener('click',()=>setOpen(!mobile.classList.contains('open')));mc.addEventListener('click',()=>setOpen(false));mobile.addEventListener('click',e=>{if(e.target.closest('a'))setOpen(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape')setOpen(false)})}
function footer(){if(indexPage||document.querySelector('.ls-canonical-footer'))return;const f=document.createElement('footer');f.className='ls-canonical-footer';f.innerHTML=`<div class="ls-footer-brand"><b>LIL</b> SYNN</div><div class="ls-footer-tag">Dark sound. Raw emotion. No limits</div><nav class="ls-footer-links"><a href="/">HOME</a><a href="/releases.html">RELEASES</a><a href="/archive.html">ARCHIVE</a><a href="/gallery.html">GALLERY</a><a href="/videos.html">VIDEOS</a><a href="/universe.html">UNIVERSE</a><a href="/#contact">CONTACT</a><a href="/#signal">SYNN SIGNAL</a></nav><nav class="ls-footer-legal"><a href="/privacy.html">PRIVACY</a><a href="/terms.html">TERMS</a></nav><div class="ls-footer-copy">© ${new Date().getFullYear()} LIL SYNN</div>`;document.body.appendChild(f)}
function normalizeLinks(){document.querySelectorAll('a[href]').forEach(a=>{const raw=a.getAttribute('href')||'';if(raw==='/vote#contact'||raw==='/index.html/contact'||raw==='/vote.html#contact')a.setAttribute('href','/#contact')})}
function init(){injectCss();bg();geometry();if(!indexPage){removeVoteShell();menu();footer()}normalizeLinks();document.body.classList.add('ls-canonical-page')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
