/* LIL SYNN index2-specific global shell. Deliberately separate from site-global.js. */
(()=>{
  const icon=(file,label,href)=>`<a class="ls2-icon" href="${href}" target="_blank" rel="noopener noreferrer" aria-label="${label}"><img src="/assets/images/icons/${file}" alt=""></a>`;
  const nav=[['Home','/index2.html'],['Music','/releases.html'],['Videos','#videos'],['Visuals','/gallery.html'],['Merch','https://lilsynnofficial.threadless.com/']];
  const menuNav=[['Home','/index2.html'],['Music','/releases.html'],['Archive','/archive.html'],['Visuals','/gallery.html'],['Universe','/universe.html'],['Videos','#videos'],['About','/index.html#about'],['Merch','https://lilsynnofficial.threadless.com/'],['Lyrics','https://genius.com/artists/Lil-synn'],['Contact','/index.html#contact']];
  const socials=[['youtube.svg','YouTube','https://www.youtube.com/@LILSYNNOFFICIAL'],['spotify.svg','Spotify','https://open.spotify.com/artist/6ozcOAnRAUPn3z5c0GR5kU'],['instagram.svg','Instagram','https://www.instagram.com/lilsynnofficial/'],['twitter.svg','X','https://x.com/lilsynnofficial'],['apple-music.svg','Apple Music','https://music.apple.com/us/artist/lil-synn/1850720041']];
  const injectCss=()=>{if(document.querySelector('link[data-ls2-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='/site-global2.css?v=20260914';l.dataset.ls2Css='true';document.head.appendChild(l)};
  const header=()=>`<header class="ls2-header" data-ls2-header><div class="ls2-header-inner"><a class="ls2-brand" href="/index2.html" aria-label="LIL SYNN home"><img src="/assets/images/icons/LS_LOGO.png" alt="LIL SYNN"></a><nav class="ls2-nav" aria-label="Primary navigation">${nav.map(([label,href])=>`<a href="${href}"${href.startsWith('http')?' target="_blank" rel="noopener noreferrer"':''}>${label}</a>`).join('')}</nav><div class="ls2-actions">${icon('spotify.svg','Spotify','https://open.spotify.com/artist/6ozcOAnRAUPn3z5c0GR5kU')}${icon('youtube.svg','YouTube','https://www.youtube.com/@LILSYNNOFFICIAL')}${icon('apple-music.svg','Apple Music','https://music.apple.com/us/artist/lil-synn/1850720041')}<span class="ls2-divider" aria-hidden="true"></span><button class="ls2-menu-toggle" type="button" aria-controls="ls2-menu" aria-expanded="false" aria-label="Open menu"><span></span><span></span><span></span></button></div></div></header>`;
  const menu=()=>`<aside class="ls2-menu" id="ls2-menu" aria-hidden="true"><div class="ls2-menu-head"><span>LIL SYNN</span><button class="ls2-menu-close" type="button" aria-label="Close menu">×</button></div><nav>${menuNav.map(([label,href])=>`<a href="${href}"${href.startsWith('http')?' target="_blank" rel="noopener noreferrer"':''}>${label}</a>`).join('')}</nav><div class="ls2-menu-socials">${socials.map(([file,label,href])=>icon(file,label,href)).join('')}</div></aside>`;
  const footer=()=>`<footer class="ls2-footer" data-ls2-footer><div class="ls2-footer-inner"><div class="ls2-footer-mailing"><div class="ls2-mailing-label">JOIN THE SIGNAL</div><form class="ls2-mailing-form" action="/index.html#contact" method="get" aria-label="Join the Signal mailing list"><input name="email" type="email" autocomplete="email" placeholder="YOUR EMAIL" aria-label="Your email address" required><button type="submit" aria-label="Continue to mailing list">→</button></form></div><div class="ls2-footer-socials">${socials.map(([file,label,href])=>icon(file,label,href)).join('')}</div><div class="ls2-footer-branding"><span>LIL SYNN</span><span class="ls2-footer-rule"></span><span>OFFICIAL</span></div><div class="ls2-footer-tag">MUSIC FOR A HIGHER FREQUENCY</div></div><div class="ls2-footer-bottom"><nav>${menuNav.slice(0,8).map(([label,href])=>`<a href="${href}"${href.startsWith('http')?' target="_blank" rel="noopener noreferrer"':''}>${label}</a>`).join('')}</nav><span>© ${new Date().getFullYear()} LIL SYNN</span></div></footer>`;
  const shell=()=>{injectCss();if(!document.querySelector('[data-ls2-header]'))document.body.insertAdjacentHTML('afterbegin',header()+menu());if(!document.querySelector('[data-ls2-footer]'))document.body.insertAdjacentHTML('beforeend',footer());document.body.classList.add('ls2-shell-ready')};
  const menuBehavior=()=>{const menuEl=document.getElementById('ls2-menu'),toggle=document.querySelector('.ls2-menu-toggle'),close=document.querySelector('.ls2-menu-close');if(!menuEl||!toggle||toggle.dataset.ready)return;toggle.dataset.ready='1';const set=open=>{menuEl.classList.toggle('open',open);menuEl.setAttribute('aria-hidden',String(!open));toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close menu':'Open menu');document.documentElement.classList.toggle('ls2-menu-open',open)};toggle.addEventListener('click',()=>set(!menuEl.classList.contains('open')));close?.addEventListener('click',()=>set(false));menuEl.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>set(false)));document.addEventListener('keydown',e=>{if(e.key==='Escape')set(false)})};
  const renderData=async()=>{
    const release=document.querySelector('[data-ls2-release]'),video=document.querySelector('[data-ls2-video]');
    try{
      const [cr,vr]=await Promise.all([fetch('/release-catalog.json',{cache:'no-store'}),fetch('/latest-videos.json',{cache:'no-store'})]);
      const catalog=await cr.json(),manifest=await vr.json();const order=Array.isArray(catalog.order)?catalog.order:[];const title=order[0];const group=catalog.groups?.[title]||{};const norm=v=>String(v??'').toLowerCase().normalize('NFKD').replace(/[’']/g,'').replace(/[^a-z0-9]+/g,'');
      const fallback={neverknown:'Never Known_album_cover.jpg',homeacousticversion:'home_acoustic_version.png',ididitagain:'I DID IT AGAIN.jpg',rescueyouacousticversion:'RESCUE_YOU_A.png',somewhereinbetween:'57_lil_synn_somewhere_in_between.jpg',blackglass:'23_lil_synn_black_glass.jpg',hellogoodbye:'11_lil_synn_hello_goodbye.jpg',heavythings:'Heavy Things_album_cover.jpg'};
      const art=title?`/assets/images/icons/album_art/${encodeURIComponent(fallback[norm(title)]||'')}`:'';
      if(release&&title){release.innerHTML=`<img src="${art}" alt="${title} artwork"><div class="ls2-card-copy"><small>LATEST RELEASE</small><h2>${title}</h2><p>LIL SYNN</p><a href="/release.html?id=${encodeURIComponent(title)}">LISTEN NOW <span>→</span></a></div>`}
      const videos=Array.isArray(manifest.videos)?manifest.videos:[];const wanted=videos.find(v=>norm(v.release)===norm(title))||videos[0];
      if(video&&wanted){video.innerHTML=`<div class="ls2-card-media"><img src="https://i.ytimg.com/vi/${encodeURIComponent(wanted.id)}/hqdefault.jpg" alt="${wanted.title}" loading="lazy"><span class="ls2-play">▶</span></div><div class="ls2-card-copy"><small>LATEST VIDEO</small><h2>${wanted.title||'THE SIGNAL'}</h2><p>OFFICIAL VIDEO</p><a href="https://www.youtube.com/watch?v=${encodeURIComponent(wanted.id)}" target="_blank" rel="noopener noreferrer">WATCH NOW <span>→</span></a></div>`}
    }catch(e){console.warn('LIL SYNN index2 content unavailable',e)}
  };
  const mailing=()=>{const form=document.querySelector('.ls2-mailing-form');if(!form||form.dataset.ready)return;form.dataset.ready='1';form.addEventListener('submit',()=>{const input=form.querySelector('input');if(input?.value)localStorage.setItem('ls2MailingEmail',input.value)})};
  const ready=()=>{shell();menuBehavior();mailing();renderData()};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready,{once:true});else ready();
})();
