(()=>{
const home=/^(\/|\/index\.html?)$/i.test(location.pathname);
const STREAM=[['Spotify','https://open.spotify.com/artist/6ozcOAnRAUPn3z5c0GR5kU'],['Apple Music','https://music.apple.com/us/artist/lil-synn/1850720041'],['YouTube','https://www.youtube.com/@LILSYNNOFFICIAL'],['iTunes','https://music.apple.com/us/artist/lil-synn/1850720041'],['YouTube Music','https://music.youtube.com/@LILSYNNOFFICIAL'],['TIDAL','https://tidal.com/artist/69300200'],['Amazon Music','https://music.amazon.com/artists/B0FZB8RWV8/lil-synn'],['iHeart','https://www.iheart.com/artist/lil-synn-48522401'],['Pandora','https://www.pandora.com/artist/lil-synn/ARZwprX4ZVXjVKc'],['Qobuz','https://www.qobuz.com/us-en/interpreter/lil-synn/29242938']];
const SOCIAL=[['YouTube','https://www.youtube.com/@LILSYNNOFFICIAL'],['Spotify','https://open.spotify.com/artist/6ozcOAnRAUPn3z5c0GR5kU'],['Apple Music','https://music.apple.com/us/artist/lil-synn/1850720041'],['Instagram','https://www.instagram.com/lilsynnofficial/'],['X / Twitter','https://x.com/lilsynnofficial'],['SoundCloud','https://soundcloud.com/lilsynnofficial'],['TikTok','https://www.tiktok.com/@lilsynnofficial'],['Facebook','https://www.facebook.com/lilsynnofficial'],['Discord','https://discord.gg/ZUVsHuCAv'],['GitHub','https://github.com/orgs/Neurosyn-Dev/repositories']];
function install(){
 if(home)return;
 const nav=document.querySelector('header .nav'); if(!nav)return;
 let ham=document.getElementById('hamburger'); if(!ham){ham=document.createElement('button');ham.id='hamburger';ham.className='text-5xl text-[#ff008f]';ham.style.marginLeft='.5rem';ham.type='button';ham.textContent='☰';nav.appendChild(ham)}
 let menu=document.getElementById('sideMenu');
 if(!menu){
  menu=document.createElement('div');menu.id='sideMenu';menu.className='fixed top-0 right-0 h-full w-72 bg-black/90 backdrop-blur-xl transform translate-x-full transition-transform duration-300 z-50';menu.setAttribute('aria-label','Site menu');
  menu.innerHTML=`<div class="flex justify-end p-6 shrink-0"><button id="closeMenu" class="text-3xl text-white hover:text-pink-500" aria-label="Close menu">&times;</button></div><nav class="flex flex-col gap-6 px-8 text-lg font-['Orbitron']"><a href="/" class="menu-link shrink-0">Home</a><a href="/#music" class="menu-link shrink-0">Music</a><a href="/releases.html" class="menu-link shrink-0">Releases</a><a href="/#videos" class="menu-link shrink-0">Videos</a><a href="/#about" class="menu-link shrink-0">About</a><a href="https://lilsynnofficial.threadless.com/" target="_blank" rel="noopener noreferrer" class="menu-link shrink-0">Merch</a><a href="https://genius.com/artists/Lil-synn" target="_blank" rel="noopener noreferrer" class="menu-link shrink-0">Lyrics</a><a href="/#contact" class="menu-link shrink-0">Contact</a><div><button id="socialsTrigger" class="menu-link flex justify-between w-full shrink-0" aria-expanded="false" aria-controls="socialsDropdown">Socials</button><div id="socialsDropdown" class="hidden flex flex-col gap-3 mt-4 pl-4 text-base font-['Rajdhani']"></div></div><div><button id="streamTrigger" class="menu-link flex justify-between w-full shrink-0" aria-expanded="false" aria-controls="streamDropdown">Stream</button><div id="streamDropdown" class="hidden flex flex-col gap-3 mt-4 pl-4 text-base font-['Rajdhani']"></div></div></nav>`;
  document.body.appendChild(menu);
  const fill=(id,items)=>{const box=document.getElementById(id);items.forEach(([name,href])=>{const a=document.createElement('a');a.href=href;a.target='_blank';a.rel='noopener noreferrer';a.className='menu-link';a.textContent=name;box.appendChild(a)})};fill('socialsDropdown',SOCIAL);fill('streamDropdown',STREAM);
 }
 ham.setAttribute('aria-label','Open navigation');ham.setAttribute('aria-controls','sideMenu');ham.setAttribute('aria-expanded','false');menu.setAttribute('aria-hidden','true');
 const setMenuState=open=>{if(!menu||!ham)return;menu.classList.toggle('translate-x-full',!open);menu.setAttribute('aria-hidden',String(!open));ham.setAttribute('aria-expanded',String(open));ham.setAttribute('aria-label',open?'Close navigation':'Open navigation');if(open){const first=menu.querySelector('a, button');if(first)setTimeout(()=>first.focus(),0)}else ham.focus()};
 ham.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();setMenuState(menu.classList.contains('translate-x-full'))});
 menu.querySelector('#closeMenu').addEventListener('click',event=>{event.preventDefault();event.stopPropagation();setMenuState(false)});
 menu.querySelectorAll('a[href^="/"]').forEach(link=>link.addEventListener('click',()=>setMenuState(false)));
 document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!menu.classList.contains('translate-x-full'))setMenuState(false)});
 const bind=(trigger,id)=>{const b=document.getElementById(trigger),list=document.getElementById(id);b.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();const open=list.classList.contains('hidden');list.classList.toggle('hidden',!open);b.setAttribute('aria-expanded',String(open))})};bind('socialsTrigger','socialsDropdown');bind('streamTrigger','streamDropdown');
 const style=document.createElement('style');style.id='index-navigation-secondary';style.textContent=`:root{--nav-height:72px;--nav-gap:.5rem}.nav{height:var(--nav-height);display:flex;align-items:center;justify-content:space-between}.nav #hamburger{margin-left:.5rem}#sideMenu{position:fixed;top:0;right:0;left:auto;bottom:auto;height:100%;width:18rem;z-index:60;overflow:hidden}#sideMenu>nav{max-height:calc(100vh - 88px);overflow-y:auto;overflow-x:hidden;overscroll-behavior:contain}@media(min-width:768px){#sideMenu>nav{height:calc(100vh - 88px);min-height:0;overflow:hidden}#sideMenu>nav>div:has(#socialsDropdown){flex:1 1 auto;min-height:0;display:flex;flex-direction:column}#sideMenu #socialsDropdown{flex:1 1 auto;min-height:0;max-height:none;overflow-y:scroll;overflow-x:hidden;overscroll-behavior:contain;padding-right:.75rem;padding-bottom:1.5rem;scrollbar-width:auto;scrollbar-color:#ff008f #111}#sideMenu #socialsDropdown::-webkit-scrollbar{width:10px}#sideMenu #socialsDropdown::-webkit-scrollbar-track{background:#111;border-radius:8px}#sideMenu #socialsDropdown::-webkit-scrollbar-thumb{background:#ff008f;border-radius:8px;border:2px solid #111}#sideMenu #socialsDropdown::-webkit-scrollbar-thumb:hover{background:#ff4fd8}}@media(max-width:640px){#sideMenu{width:min(86vw,360px)}#sideMenu>nav{max-height:calc(100vh - 82px);padding-bottom:1.5rem}.nav #hamburger{font-size:1.4rem;height:44px}}`;document.head.appendChild(style);
}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install,{once:true}):install();
})();