(()=>{
const home=/^(\/|\/index\.html?)$/i.test(location.pathname);
const SRC='/assets/other/sound/Background.mp3',KEY='lilSynnTheCalmStateV4',API='https://api.github.com/repos/LILSYNNOFFICIAL/LILSYNNOFFICIAL/contents/assets/mov?ref=main';
const MENU=[['Home','/'],['Music','/#music'],['Releases','/releases.html'],['Videos','/#videos'],['About','/#about'],['Merch','https://lilsynnofficial.threadless.com/'],['Lyrics','https://genius.com/artists/Lil-synn'],['Contact','/#contact'],['Privacy','/privacy.html'],['Terms','/terms.html']];
function css(){if(document.getElementById('lsg'))return;const s=document.createElement('style');s.id='lsg';s.textContent=`
body.lsg-secondary{min-height:100dvh;display:flex;flex-direction:column}body.lsg-secondary>main{flex:1 0 auto}body.lsg-secondary>footer{flex:0 0 auto}
#lilSynnGlobalNav{display:flex;align-items:center;margin-left:auto;height:72px;z-index:10000}
#lilSynnGlobalNav button{width:auto;height:48px;padding:0;border:0;background:transparent;color:#ff008f;font:400 48px/1 Arial;cursor:pointer}
#lilSynnGlobalMenu{position:fixed;top:0;right:0;z-index:9999;width:min(360px,88vw);height:100dvh;padding:78px 24px 28px;box-sizing:border-box;background:#000f;backdrop-filter:blur(18px);transform:translateX(102%);transition:transform .25s ease;overflow:auto;border-left:1px solid #ff008f59}
#lilSynnGlobalMenu.open{transform:none}
#lilSynnGlobalMenu a{display:block;padding:11px 4px;color:#fff!important;text-decoration:none;font:600 17px/1.25 Rajdhani,Arial;letter-spacing:.06em;border-bottom:1px solid #fff1}
#lilSynnGlobalMenu button{color:#fff;cursor:pointer}
#lilSynnCalm{width:min(92vw,900px);margin:2rem auto;padding:.65rem .8rem;display:flex;align-items:center;gap:.7rem;background:#000b;border:1px solid #fff3;border-radius:12px;box-sizing:border-box;color:#fff;position:relative;z-index:100}
#lilSynnCalm strong{white-space:nowrap;color:#fff}
#lilSynnCalm [data-calm-seek]{flex:1;min-width:60px}
#lilSynnCalm [data-calm-volume]{width:90px}
#lilSynnFooterCredit{padding:12px 16px 28px;text-align:center;color:#fff;font:600 13px/1.4 Rajdhani,Arial;letter-spacing:.05em}
@media(max-width:600px){#lilSynnGlobalNav{height:56px}#lilSynnGlobalNav button{font-size:40px;height:44px}#lilSynnGlobalMenu{width:min(340px,92vw)}#lilSynnCalm{flex-wrap:wrap}#lilSynnCalm [data-calm-seek]{order:3;flex-basis:100%}#lilSynnCalm [data-calm-volume]{width:80px}}
#siteBgVideo{object-fit:cover!important;object-position:center center!important}
.release .links a[href*="open.spotify.com"],.single .links a[href*="open.spotify.com"]{background:#1ed760!important;color:#000!important;border-color:#1ed760!important}
.release .links a[href*="music.apple.com"],.single .links a[href*="music.apple.com"]{background:#ff008f!important;color:#050505!important;border-color:#ff008f!important}
`;
document.head.appendChild(s)}
function ensureFooter(){let f=document.querySelector('footer');if(!f){f=document.createElement('footer');f.id='lilSynnGeneratedFooter';document.body.appendChild(f)}f.style.marginTop='auto';f.style.position='relative';f.style.zIndex='10';let credits=[...f.querySelectorAll('#lilSynnFooterCredit,[data-site-credit]')];credits.slice(1).forEach(x=>x.remove());let c=credits[0];if(!c){c=document.createElement('div');c.id='lilSynnFooterCredit';c.dataset.siteCredit='true';f.appendChild(c)}c.textContent='Designed with ChatGPT | Synova Media'}
function nav(){if(document.getElementById('hamburger')||document.getElementById('sideMenu')||document.getElementById('lilSynnGlobalNav'))return;const n=document.createElement('div');n.id='lilSynnGlobalNav';const b=document.createElement('button');b.type='button';b.textContent='☰';b.setAttribute('aria-label','Open navigation');b.setAttribute('aria-controls','lilSynnGlobalMenu');b.setAttribute('aria-expanded','false');const m=document.createElement('div');m.id='lilSynnGlobalMenu';const x=document.createElement('button');x.type='button';x.textContent='×';x.setAttribute('aria-label','Close navigation');x.style='position:absolute;top:18px;right:18px;width:42px;height:42px;background:#090909;color:#fff;border:1px solid #ff008f73;border-radius:10px;font-size:28px';m.append(x);MENU.forEach(([label,url])=>{const a=document.createElement('a');a.href=url;a.textContent=label;if(/^https?:/.test(url)){a.target='_blank';a.rel='noopener noreferrer'}m.append(a)});const set=v=>{m.classList.toggle('open',v);b.setAttribute('aria-expanded',String(v))};b.addEventListener('click',()=>set(!m.classList.contains('open')));x.addEventListener('click',()=>set(false));document.addEventListener('keydown',e=>{if(e.key==='Escape')set(false)});const h=document.querySelector('header'),r=h?.querySelector('.nav');(r||h||document.body).append(n);document.body.append(m)}
function ensureBackground(){let v=document.getElementById('siteBgVideo');if(!v){v=document.createElement('video');v.id='siteBgVideo';v.autoplay=true;v.loop=true;v.muted=true;v.playsInline=true;v.setAttribute('aria-hidden','true');const o=document.createElement('div');o.id='siteBgOverlay';o.setAttribute('aria-hidden','true');document.body.prepend(o);document.body.prepend(v)}return v}
function calm(){let a=document.getElementById('bgMusic');if(!a){a=document.createElement('audio');a.id='bgMusic';a.src=SRC;a.loop=true;a.preload='metadata';a.style.display='none';document.body.append(a)}let st={};try{st=JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{}if(Number.isFinite(st.volume))a.volume=st.volume;if(typeof st.muted==='boolean')a.muted=st.muted;const save=()=>{try{localStorage.setItem(KEY,JSON.stringify({time:a.currentTime||0,playing:!a.paused&&!a.ended,volume:a.volume,muted:a.muted}))}catch{}};let p=document.getElementById('lilSynnCalm');if(!p){p=document.createElement('div');p.id='lilSynnCalm';p.innerHTML='<strong>THE CALM <span>• LIL SYNN</span></strong><button type="button" data-calm-toggle aria-label="Play or pause The Calm">▶</button><input data-calm-seek type="range" min="0" max="100" value="0" step=".1" aria-label="The Calm progress"><input data-calm-volume type="range" min="0" max="1" value=".65" step=".01" aria-label="The Calm volume"><button type="button" data-calm-mute aria-label="Mute The Calm">🔊</button>';const f=document.querySelector('footer');(f?f.parentNode:document.body).insertBefore(p,f||null);const t=p.querySelector('[data-calm-toggle]'),m=p.querySelector('[data-calm-mute]'),v=p.querySelector('[data-calm-volume]'),s=p.querySelector('[data-calm-seek]');v.value=a.muted?0:a.volume;m.textContent=a.muted?'🔇':'🔊';t.onclick=e=>{e.preventDefault();e.stopPropagation();a.paused?a.play().catch(()=>{}):a.pause();save()};m.onclick=e=>{e.preventDefault();e.stopPropagation();a.muted=!a.muted;m.textContent=a.muted?'🔇':'🔊';save()};v.oninput=e=>{a.volume=+e.target.value;a.muted=a.volume===0;save()};s.oninput=e=>{if(a.duration)a.currentTime=+e.target.value/100*a.duration};a.ontimeupdate=()=>{if(a.duration)s.value=a.currentTime/a.duration*100};a.onvolumechange=()=>{v.value=a.muted?0:a.volume;m.textContent=a.muted||a.volume===0?'🔇':'🔊'};a.onplay=()=>t.textContent='❚❚';a.onpause=()=>t.textContent='▶'}if(Number.isFinite(st.time)){const r=()=>{if(!a.duration||st.time<a.duration)a.currentTime=st.time};a.readyState>=1?r():a.addEventListener('loadedmetadata',r,{once:true})}if(st.playing)a.play().catch(()=>{});a.addEventListener('timeupdate',save);window.addEventListener('pagehide',save);return a}
async function bg(){const v=ensureBackground();try{const c=new AbortController(),t=setTimeout(()=>c.abort(),2000),r=await fetch(API,{cache:'force-cache',signal:c.signal});clearTimeout(t);if(!r.ok)throw 0;const fs=await r.json(),p=fs.filter(x=>x.type==='file'&&/\.webm$/i.test(x.name));if(!p.length)return;v.src='/assets/mov/'+encodeURIComponent(p[Math.random()*p.length|0].name);v.load();v.play().catch(()=>{})}catch{}}
function spotify(a){document.querySelectorAll('iframe[src*="open.spotify.com"]').forEach(f=>{if(f.dataset.calm)return;f.dataset.calm='1';f.addEventListener('pointerdown',()=>{if(!a.paused){a.pause();try{localStorage.setItem(KEY,JSON.stringify({time:a.currentTime,playing:true,volume:a.volume,muted:a.muted}))}catch{}}},{capture:true,passive:true})})}
function init(){css();ensureFooter();if(home)return;document.body.classList.add('lsg-secondary');nav();const a=calm();bg();spotify(a)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init()
})();