(() => {
  'use strict';
  const $ = s => document.querySelector(s);
  const $$ = s => [...document.querySelectorAll(s)];
  const KEY = 'ls-visual-designer-v1';
  const requiredIds = ['stage','pageFrame','layers','inspector','status','viewportSelect','zoom'];
  const tools = ['select','hand','grid','snap','guides','rulers','layers','assets','preview','code'];
  const breakpoints = {desktop:{w:1440,h:900},tablet:{w:900,h:900},mobile:{w:390,h:844}};
  const editable = ['position','top','right','bottom','left','inset','width','height','min-width','max-width','min-height','max-height','margin','margin-top','margin-right','margin-bottom','margin-left','padding','padding-top','padding-right','padding-bottom','padding-left','display','flex','flex-direction','flex-wrap','flex-grow','flex-shrink','flex-basis','justify-content','align-items','align-content','gap','grid-template-columns','grid-template-rows','font-family','font-size','font-weight','line-height','letter-spacing','text-align','text-transform','color','background','background-color','border','border-width','border-style','border-color','border-radius','box-shadow','opacity','translate','z-index','overflow','visibility'];
  const state = { route:'/index.html', breakpoint:'desktop', zoom:60, tool:'select', selected:null, locked:new Set(), hidden:new Set(), grid:false, snap:true, guides:true, rulers:false, preview:false, code:false, history:[], future:[], patches:{desktop:{},tablet:{},mobile:{}} };
  let frameDoc = null, drag = null, resize = null;

  const clone = v => JSON.parse(JSON.stringify(v));
  const snapshot = () => ({patches:clone(state.patches),selected:state.selected,breakpoint:state.breakpoint,zoom:state.zoom,grid:state.grid,snap:state.snap,guides:state.guides,rulers:state.rulers});
  function restore(s){state.patches=clone(s.patches);state.selected=s.selected;state.breakpoint=s.breakpoint;state.zoom=s.zoom;state.grid=s.grid;state.snap=s.snap;state.guides=s.guides;state.rulers=s.rulers;applyAll();renderAll()}
  function pushHistory(){state.history.push(snapshot());if(state.history.length>80)state.history.shift();state.future=[];}
  function undo(){if(!state.history.length)return;state.future.push(snapshot());restore(state.history.pop());toast('Undo')}
  function redo(){if(!state.future.length)return;state.history.push(snapshot());restore(state.future.pop());toast('Redo')}
  function toast(text){const old=$('.toast');if(old)old.remove();const t=document.createElement('div');t.className='toast';t.textContent=text;document.body.append(t);setTimeout(()=>t.remove(),1800)}
  function selector(el){if(!el||el===frameDoc.body||el===frameDoc.documentElement)return 'body';if(el.id&&/^[A-Za-z][\w-]*$/.test(el.id))return '#'+CSS.escape(el.id);const parts=[];let n=el;while(n&&n.nodeType===1&&n!==frameDoc.body){let p=n.parentElement;if(!p)break;let same=[...p.children].filter(x=>x.tagName===n.tagName);let part=n.tagName.toLowerCase();if(same.length>1)part+=`:nth-of-type(${same.indexOf(n)+1})`;parts.unshift(part);n=p}return 'body>'+parts.join('>')}
  function find(sel){try{return frameDoc?.querySelector(sel)||null}catch{return null}}
  function isEditableElement(el){if(!el||!frameDoc)return false;return el!==frameDoc.body&&el!==frameDoc.documentElement&&!!el.tagName}
  function patchFor(sel,bp=state.breakpoint){return state.patches[bp][sel]||(state.patches[bp][sel]={})}
  function setProp(prop,value){if(!state.selected||!editable.includes(prop))return;pushHistory();patchFor(state.selected)[prop]=String(value);applySelected();renderInspector();setDirty()}
  function removeProp(prop){if(!state.selected)return;const p=patchFor(state.selected);if(!(prop in p))return;pushHistory();delete p[prop];applySelected();renderInspector();setDirty()}
  function applyPatch(el,patch){if(!el)return;for(const [k,v] of Object.entries(patch)){if(editable.includes(k))el.style.setProperty(k,v,'important')}}
  function applyAll(){if(!frameDoc)return;for(const bp of Object.keys(state.patches)){if(bp!==state.breakpoint)continue;for(const [sel,p] of Object.entries(state.patches[bp]))applyPatch(find(sel),p)}}
  function applySelected(){const el=find(state.selected);if(!el)return;applyPatch(el,patchFor(state.selected));updateOverlay()}
  function visibleElements(){if(!frameDoc?.body)return[];return [...frameDoc.body.querySelectorAll('*')].filter(el=>{const r=el.getBoundingClientRect();const cs=frameDoc.defaultView.getComputedStyle(el);return r.width>3&&r.height>3&&cs.visibility!=='hidden'&&cs.display!=='none'}).slice(0,220)}
  function renderLayers(){const q=($('#layerSearch')?.value||'').toLowerCase();const box=$('#layers');if(!box)return;box.innerHTML='';visibleElements().filter(el=>{const text=(el.tagName+' '+(el.id||'')+' '+(el.className||'')).toLowerCase();return !q||text.includes(q)}).forEach(el=>{const sel=selector(el),row=document.createElement('div');row.className='layer'+(sel===state.selected?' selected':'');row.dataset.selector=sel;row.innerHTML=`<span class="tag">${el.tagName.toLowerCase()}</span><span class="name">${el.id?'#'+el.id:(el.textContent||'').trim().slice(0,34)||sel}</span><span class="eye">${state.hidden.has(sel)?'◌':'●'}</span><span class="lock">${state.locked.has(sel)?'◆':'◇'}</span>`;row.onclick=()=>selectElement(sel);box.append(row)})}
  function selectElement(sel){if(!sel||!find(sel))return;state.selected=sel;renderLayers();renderInspector();updateOverlay();setStatus('Selected '+sel)}
  function rectRelative(el){const r=el.getBoundingClientRect();return {left:r.left,top:r.top,width:r.width,height:r.height}}
  function updateOverlay(){const ov=$('#overlay');if(!ov||!frameDoc)return;ov.innerHTML='';if(!state.selected)return;const el=find(state.selected);if(!el)return;const r=rectRelative(el);const box=document.createElement('div');box.className='selection';box.style.left=r.left+'px';box.style.top=r.top+'px';box.style.width=r.width+'px';box.style.height=r.height+'px';const label=document.createElement('div');label.className='label';label.textContent=state.selected;box.append(label);['nw','n','ne','e','se','s','sw','w'].forEach(h=>{const d=document.createElement('div');d.className='handle '+h;d.dataset.handle=h;d.onpointerdown=e=>startResize(e,h);box.append(d)});ov.append(box);if(state.guides){const gx=document.createElement('div');gx.className='guide x';gx.style.left=(r.left+r.width/2)+'px';const gy=document.createElement('div');gy.className='guide y';gy.style.top=(r.top+r.height/2)+'px';ov.append(gx,gy)}}
  function startDrag(e,el){if(state.tool!=='select'||state.locked.has(state.selected))return;e.preventDefault();e.stopPropagation();pushHistory();const r=rectRelative(el);const p=patchFor(state.selected);const oldX=parseFloat(p.translate?.match(/[-\d.]+/g)?.[0]||0),oldY=parseFloat(p.translate?.match(/[-\d.]+/g)?.[1]||0);drag={x:e.clientX,y:e.clientY,oldX,oldY};el.setPointerCapture?.(e.pointerId)}
  function updateDrag(e){if(!drag||!state.selected)return;const el=find(state.selected);if(!el)return;let x=drag.oldX+e.clientX-drag.x,y=drag.oldY+e.clientY-drag.y;if(state.snap){x=Math.round(x/10)*10;y=Math.round(y/10)*10}patchFor(state.selected).translate=`${x}px ${y}px`;applySelected()}
  function endDrag(){if(drag){drag=null;setDirty()}}
  function startResize(e,h){e.preventDefault();e.stopPropagation();if(state.locked.has(state.selected))return;const el=find(state.selected);if(!el)return;pushHistory();const r=rectRelative(el);resize={h,x:e.clientX,y:e.clientY,w:r.width,h0:r.height,left:r.left,top:r.top};window.addEventListener('pointermove',moveResize);window.addEventListener('pointerup',endResize,{once:true})}
  function moveResize(e){if(!resize||!state.selected)return;let w=resize.w,h=resize.h0;if(/e|w/.test(resize.h))w=resize.w+(resize.h.includes('e')?1:-1)*(e.clientX-resize.x);if(/n|s/.test(resize.h))h=resize.h0+(resize.h.includes('s')?1:-1)*(e.clientY-resize.y);w=Math.max(20,w);h=Math.max(20,h);if(state.snap){w=Math.round(w/10)*10;h=Math.round(h/10)*10}const p=patchFor(state.selected);p.width=Math.round(w)+'px';p.height=Math.round(h)+'px';applySelected();renderInspector()}
  function endResize(){resize=null;window.removeEventListener('pointermove',moveResize);setDirty()}
  function bindFrame(){frameDoc= $('#pageFrame').contentDocument;if(!frameDoc)return;const style=frameDoc.createElement('style');style.id='ls-editor-bridge';style.textContent=`html{scroll-behavior:auto!important}.ls-designer-hover{outline:1px dashed #ffd21a!important;cursor:move!important}.ls-designer-hidden{display:none!important}`;frameDoc.head.append(style);frameDoc.addEventListener('pointerover',e=>{if(state.tool==='select'&&isEditableElement(e.target))e.target.classList.add('ls-designer-hover')},true);frameDoc.addEventListener('pointerout',e=>e.target?.classList?.remove('ls-designer-hover'),true);frameDoc.addEventListener('pointerdown',e=>{if(state.tool!=='select'||!isEditableElement(e.target))return;const el=e.target;const sel=selector(el);if(state.locked.has(sel))return;selectElement(sel);startDrag(e,el)},true);frameDoc.addEventListener('pointermove',updateDrag,true);frameDoc.addEventListener('pointerup',endDrag,true);frameDoc.addEventListener('click',e=>{if(state.tool==='select'){e.preventDefault();e.stopPropagation()}},true);applyAll();renderLayers();updateOverlay();setStatus('Page loaded — click an element to edit')}
  function setViewport(){const bp=breakpoints[state.breakpoint];const wrap=$('.stage-wrap');wrap.style.width=Math.min(bp.w,window.innerWidth*0.9)+'px';wrap.style.height=Math.min(bp.h,window.innerHeight*0.82)+'px';$('#pageFrame').style.width=bp.w+'px';$('#pageFrame').style.height=bp.h+'px';$('#pageFrame').style.transform=`scale(${state.zoom/100})`;$('#pageFrame').style.transformOrigin='top left';$('.stage').style.width=(bp.w*state.zoom/100)+'px';$('.stage').style.height=(bp.h*state.zoom/100)+'px';$('.stage-wrap').style.width=(bp.w*state.zoom/100)+'px';$('.stage-wrap').style.height=(bp.h*state.zoom/100)+'px';updateOverlay()}
  function renderInspector(){const box=$('#inspector');if(!box)return;box.innerHTML='';if(!state.selected){box.innerHTML='<div class="ins-head"><div class="eyebrow">INSPECTOR</div><div class="small">Select something on the page.</div></div>';return}const el=find(state.selected),cs=frameDoc.defaultView.getComputedStyle(el),p=patchFor(state.selected);box.innerHTML=`<div class="ins-head"><div class="eyebrow">INSPECTOR</div><strong>${state.selected}</strong><div class="small">${el.textContent?.trim().slice(0,90)||el.tagName}</div></div>`;addSection(box,'Layout',[['position','Position',cs.position],['top','Top',cs.top],['left','Left',cs.left],['width','Width',cs.width],['height','Height',cs.height],['margin','Margin',cs.margin],['padding','Padding',cs.padding],['display','Display',cs.display],['gap','Gap',cs.gap],['z-index','Layer',cs.zIndex]]);addSection(box,'Typography',[['font-family','Font',cs.fontFamily],['font-size','Size',cs.fontSize],['font-weight','Weight',cs.fontWeight],['line-height','Line height',cs.lineHeight],['letter-spacing','Letter spacing',cs.letterSpacing],['text-align','Alignment',cs.textAlign],['text-transform','Case',cs.textTransform],['color','Text color',cs.color]]);addSection(box,'Appearance',[['background-color','Background',cs.backgroundColor],['border','Border',cs.border],['border-radius','Radius',cs.borderRadius],['box-shadow','Shadow',cs.boxShadow],['opacity','Opacity',cs.opacity],['translate','Move',p.translate||cs.translate]]);addSection(box,'Advanced',[['overflow','Overflow',cs.overflow],['visibility','Visibility',cs.visibility],['flex-direction','Flex direction',cs.flexDirection],['justify-content','Justify',cs.justifyContent],['align-items','Align',cs.alignItems]]);const actions=document.createElement('div');actions.className='actions';actions.innerHTML='<button class="tool" id="dup">DUPLICATE</button><button class="tool" id="hide">HIDE</button><button class="tool" id="lock">LOCK</button><button class="tool" id="resetSel">RESET</button>';box.append(actions);$('#dup').onclick=duplicateSelected;$('#hide').onclick=()=>toggleHidden(state.selected);$('#lock').onclick=()=>toggleLock(state.selected);$('#resetSel').onclick=resetSelected}
  function addSection(parent,title,fields){const d=document.createElement('details');d.className='section';d.open=title==='Layout';d.innerHTML=`<summary>${title.toUpperCase()}</summary>`;const grid=document.createElement('div');grid.className='fields';fields.forEach(([prop,label,value])=>{const f=document.createElement('div');f.className='field';f.innerHTML=`<label>${label}</label><input data-prop="${prop}" value="${String(patchFor(state.selected)[prop]??value??'').replaceAll('&','&amp;').replaceAll('"','&quot;')}">`;grid.append(f)});d.append(grid);parent.append(d);grid.querySelectorAll('input').forEach(i=>{i.onchange=()=>setProp(i.dataset.prop,i.value);i.onkeydown=e=>{if(e.key==='Enter')setProp(i.dataset.prop,i.value)}})}
  function duplicateSelected(){const el=find(state.selected);if(!el)return;pushHistory();const p=clone(patchFor(state.selected));p.translate=`${(parseFloat(p.translate)||0)+20}px ${(parseFloat(p.translate?.match(/[-\d.]+/g)?.[1])||0)+20}px`;const n={...p};const sel=state.selected;state.patches[state.breakpoint][sel]=p;applySelected();toast('Duplicate offset added — use page structure for true DOM duplication')}
  function toggleHidden(sel){pushHistory();if(state.hidden.has(sel))state.hidden.delete(sel);else state.hidden.add(sel);const p=patchFor(sel);p.visibility=state.hidden.has(sel)?'hidden':'visible';applySelected();renderInspector();renderLayers();setDirty()}
  function toggleLock(sel){if(state.locked.has(sel))state.locked.delete(sel);else state.locked.add(sel);renderLayers();renderInspector()}
  function resetSelected(){if(!state.selected)return;pushHistory();delete state.patches[state.breakpoint][state.selected];applyAll();renderInspector();updateOverlay();setDirty()}
  function setTool(t){state.tool=t;$$('.tool[data-tool]').forEach(x=>x.classList.toggle('active',x.dataset.tool===t));document.body.classList.toggle('preview',t==='preview');if(t==='preview'){state.preview=true;$('#pageFrame').style.pointerEvents='auto'}else{state.preview=false;$('#pageFrame').style.pointerEvents='none'}setStatus(t.toUpperCase()+' TOOL')}
  function setDirty(){state.dirty=true;setStatus('Unsaved layout changes')}
  function setStatus(s){$('#status').innerHTML=`<strong>${s}</strong>`}
  function saveDraft(){localStorage.setItem(KEY,JSON.stringify({version:1,patches:state.patches}));state.dirty=false;setStatus('Draft saved locally');toast('Draft saved')}
  function loadDraft(){try{const d=JSON.parse(localStorage.getItem(KEY)||'null');if(!d?.patches)return false;state.patches=d.patches;applyAll();renderAll();setStatus('Draft loaded');return true}catch{return false}}
  function exportPatch(){const entries=[];for(const [bp,map] of Object.entries(state.patches))for(const [sel,props] of Object.entries(map))entries.push({breakpoint:bp,selector:sel,properties:props});return entries}
  async function getBaseSha(){const r=await fetch('/api/admin?action=commits');if(!r.ok)throw new Error('AUTH_REQUIRED');const d=await r.json();return d.commits?.[0]?.sha||''}
  async function saveGithub(){try{setStatus('Preparing GitHub save…');const baseSha=await getBaseSha();const patch=exportPatch();if(!patch.length){toast('Nothing to save');return}const r=await fetch('/api/admin?action=save-layout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmation:'SAVE LAYOUT',baseSha,patch})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'SAVE_FAILED');state.dirty=false;setStatus('Saved to GitHub — '+d.sha.slice(0,8));toast('GitHub commit created')}catch(e){setStatus('Save failed: '+e.message);toast('Save failed')}}
  function codeView(){const pre=$('#code');pre.textContent=exportPatch().map(x=>`/* ${x.breakpoint} ${x.selector} */\n${Object.entries(x.properties).map(([k,v])=>`  ${k}: ${v};`).join('\n')}`).join('\n\n')||'/* No edits yet. */';pre.classList.toggle('hidden',!state.code);state.code=!state.code;pre.classList.toggle('hidden',!state.code)}
  function renderAll(){setViewport();renderLayers();renderInspector();updateOverlay()}
  function wire(){ $('#pageFrame').addEventListener('load',bindFrame);$('#viewportSelect').onchange=e=>{pushHistory();state.breakpoint=e.target.value;renderAll()};$('#zoom').oninput=e=>{state.zoom=+e.target.value;renderAll()};$('#undo').onclick=undo;$('#redo').onclick=redo;$('#draft').onclick=saveDraft;$('#loadDraft').onclick=()=>{loadDraft();toast('Draft loaded')};$('#saveGithub').onclick=saveGithub;$('#preview').onclick=()=>setTool(state.preview?'select':'preview');$('#codeToggle').onclick=codeView;$('#reset').onclick=()=>{if(confirm('Reset all unsaved editor changes?')){state.patches={desktop:{},tablet:{},mobile:{}};state.history=[];state.future=[];applyAll();renderAll();setStatus('Editor reset')}};$$('.tool[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$('#gridToggle').onclick=()=>{state.grid=!state.grid;$('.grid-overlay').classList.toggle('hidden',!state.grid)};$('#snapToggle').onclick=()=>{state.snap=!state.snap;$('#snapToggle').classList.toggle('active',state.snap)};$('#guideToggle').onclick=()=>{state.guides=!state.guides;updateOverlay()};$('#layerSearch').oninput=renderLayers;window.addEventListener('resize',renderAll);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.key==='Escape')setTool('select');else if(state.selected&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();pushHistory();const p=patchFor(state.selected),m=e.shiftKey?10:1,v=(p.translate||'0px 0px').match(/[-\d.]+/g)||['0','0'];let x=+v[0]||0,y=+v[1]||0;if(e.key==='ArrowUp')y-=m;if(e.key==='ArrowDown')y+=m;if(e.key==='ArrowLeft')x-=m;if(e.key==='ArrowRight')x+=m;p.translate=`${x}px ${y}px`;applySelected();setDirty()}})}
  function login(){const card=$('#login');const form=$('#loginForm');form.onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='AUTHENTICATING…';try{const r=await fetch('/api/admin?action=login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#email').value,password:$('#password').value})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'INVALID_CREDENTIALS');card.classList.add('hidden');$('.designer').classList.remove('hidden');init()}catch(err){$('#loginError').textContent=err.message}}}
  async function init(){wire();setViewport();loadDraft();$('#pageFrame').src=state.route;setTool('select')}
  async function boot(){login();try{const r=await fetch('/api/admin?action=session');if(r.ok){$('#login').classList.add('hidden');$('.designer').classList.remove('hidden');init()}}catch{}}
  window.LSDesignerTestHooks={requiredIds,version:1,historyRoundTrip(){const a={x:1};const b=clone(a);b.x=2;return a.x===1&&b.x===2},patchRoundTrip(){const p={desktop:{'#hero':{left:'10px',color:'#ffd21a'}}};return JSON.parse(JSON.stringify(p)).desktop['#hero'].left==='10px'},draftRoundTrip(){const p={desktop:{'#hero':{width:'100px'}}};return JSON.parse(JSON.stringify(p)).desktop['#hero'].width==='100px'},toolRegistryValid(){return tools.length===10&&tools.every(Boolean)},serialize:exportPatch};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();