(() => {
  'use strict';
  const KEY='ls-designer-dom-v2';
  const frame=()=>document.querySelector('#pageFrame')?.contentDocument||null;
  const toast=t=>{const n=document.createElement('div');n.className='toast';n.textContent=t;document.body.append(n);setTimeout(()=>n.remove(),1800)};
  let deleted=[];
  function stableId(el){if(!el.dataset.lsId)el.dataset.lsId='el_'+Math.random().toString(36).slice(2,10);return el.dataset.lsId}
  function markCreated(el){if(!el)return;el.dataset.lsDesigner='1';stableId(el);el.querySelectorAll?.('*').forEach(n=>{n.dataset.lsDesigner='1';stableId(n)})}
  function serializeFallback(el){const attrs={};for(const a of ['class','title','alt','href','src','target','rel','controls','autoplay','muted','loop','poster','type','aria-label','role'])if(el.hasAttribute(a))attrs[a]=el.getAttribute(a);const style={};for(const k of ['position','top','right','bottom','left','width','height','min-width','max-width','min-height','max-height','margin','padding','display','flex','flex-direction','flex-wrap','flex-grow','flex-shrink','flex-basis','justify-content','align-items','gap','font-family','font-size','font-weight','line-height','letter-spacing','text-align','text-transform','color','background','background-color','border','border-width','border-style','border-color','border-radius','box-shadow','opacity','z-index','overflow','object-fit'])if(el.style[k])style[k]=el.style[k];return{id:stableId(el),tag:el.tagName.toLowerCase(),attrs,style,text:el.childElementCount?'':(el.textContent||'').slice(0,10000),parentSelector:null,parentId:null,index:0}}
  function created(){const d=frame();if(!d)return[];if(window.LSDesignerStructure?.collectCreated)return window.LSDesignerStructure.collectCreated();return[...d.querySelectorAll('[data-ls-designer="1"]')].filter(el=>!el.parentElement?.closest('[data-ls-designer="1"]')).map(serializeFallback)}
  async function baseSha(){const r=await fetch('/api/admin?action=commits');if(!r.ok)throw Error('AUTH_REQUIRED');const d=await r.json();return d.commits?.[0]?.sha||''}
  async function save(){try{const made=created();const payload={confirmation:'SAVE DOM',baseSha:await baseSha(),created:made,deleted:[...new Set(deleted)]};if(!payload.created.length&&!payload.deleted.length){toast('No DOM changes to save');return}const r=await fetch('/api/designer-dom',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error||'SAVE_DOM_FAILED');localStorage.removeItem(KEY);deleted=[];toast('DOM saved to GitHub');document.querySelector('#status').innerHTML='<strong>DOM saved to GitHub</strong>'}catch(e){toast(e.message||'Save failed');document.querySelector('#status').innerHTML='<strong>DOM save failed — local edits preserved</strong>'}}
  function rememberDelete(el){if(!el)return;if(el.dataset.lsDesigner==='1')el.remove();else{const d=frame();const sel=d&&el.id&&/^[A-Za-z][\w-]*$/.test(el.id)?'#'+CSS.escape(el.id):null;if(sel)deleted.push(sel);el.style.setProperty('display','none','important')}}
  function editText(){const d=frame();const label=document.querySelector('#overlay .selection .label');if(!d||!label)return toast('Select text first');let el;try{el=d.querySelector(label.textContent)}catch{}if(!el)return toast('Select an element first');const before=el.textContent||'';el.contentEditable='true';el.focus();const finish=()=>{el.contentEditable='false';if(el.textContent!==before){markCreated(el);toast('Text changed — save DOM to persist')}};el.addEventListener('blur',finish,{once:true})}
  function init(){const toolbar=document.querySelector('.toolbar');if(toolbar&&!document.querySelector('#saveDom')){const b=document.createElement('button');b.id='saveDom';b.className='tool save';b.textContent='SAVE DOM';b.onclick=save;toolbar.insertBefore(b,document.querySelector('#saveGithub'))}const d=frame();if(d?.body)new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType===1&&n.dataset?.lsDesigner==='1')markCreated(n)}))).observe(d.body,{childList:true,subtree:true});window.LSDesignerPersist={version:2,save,markCreated,rememberDelete,editText,serialize:serializeFallback,getStructure:()=>({created:created(),deleted:[...deleted],operations:window.LSDesignerStructure?.pending?.()||[]})};window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='e'){e.preventDefault();editText()}})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
