(() => {
  'use strict';
  const KEY='ls-visual-designer-plus-v1';
  const $=s=>document.querySelector(s);
  const $$=s=>[...document.querySelectorAll(s)];
  const plus={enabled:true,history:[],future:[],patches:{desktop:{},tablet:{},mobile:{}}};
  const safe=(v,max=240)=>String(v??'').slice(0,max).replace(/[{};<>`]/g,'');
  function selected(){const label=$('#overlay .selection .label');return label?.textContent||null}
  function frame(){return $('#pageFrame')?.contentDocument||null}
  function el(){const d=frame(),s=selected();try{return d&&s?d.querySelector(s):null}catch{return null}}
  function bp(){return $('#viewportSelect')?.value||'desktop'}
  function snap(v){return $('#snapToggle')?.classList.contains('active')?Math.round(v/10)*10:v}
  function commit(prop,value){const s=selected();if(!s)return;plus.patches[bp()][s]??={};plus.patches[bp()][s][prop]=safe(value);apply();toast('Applied')}
  function apply(){const d=frame();if(!d)return;for(const [s,p] of Object.entries(plus.patches[bp()])){let x;try{x=d.querySelector(s)}catch{}if(!x)continue;for(const [k,v] of Object.entries(p))x.style.setProperty(k,v,'important')} }
  function history(){plus.history.push(JSON.stringify(plus.patches));if(plus.history.length>60)plus.history.shift();plus.future=[]}
  function change(prop,value){history();commit(prop,value);saveLocal()}
  function move(dx,dy){const x=el();if(!x)return;history();const cs=frame().defaultView.getComputedStyle(x);const m=cs.transform.match(/matrix\([^,]+,[^,]+,[^,]+,[^,]+,\s*([\d.-]+),\s*([\d.-]+)\)/);let ox=m?+m[1]:0,oy=m?+m[2]:0;const p=plus.patches[bp()][selected()]||{};const t=String(p.translate||'').match(/-?\d+(?:\.\d+)?/g);if(t){ox=+t[0]||0;oy=+t[1]||0}commit('translate',`${snap(ox+dx)}px ${snap(oy+dy)}px`);saveLocal()}
  function duplicate(){const x=el();if(!x)return;history();const s=selected();plus.patches[bp()][s]??={};const old=plus.patches[bp()][s].translate||'0px 0px';const n=old.match(/-?\d+(?:\.\d+)?/g)||['0','0'];plus.patches[bp()][s].translate=`${+n[0]+20}px ${+n[1]+20}px`;apply();saveLocal();toast('Duplicate offset — use DOM insert for new elements')}
  function remove(){const x=el();if(!x)return;history();const s=selected();commit('display','none');saveLocal();toast('Hidden — reset to restore')}
  function editText(){const x=el();if(!x)return;const old=x.innerText;const value=prompt('Edit visible text:',old);if(value===null)return;history();x.innerText=value;const d=frame();const style=d.createElement('style');style.dataset.lsText='1';style.textContent=`${safesel(selected())}{}`;d.head.append(style);plus.patches[bp()][selected()]??={};plus.patches[bp()][selected()]['--ls-designer-text']=safe(value);saveLocal();toast('Text changed in preview')}
  function safesel(s){return /^[#A-Za-z0-9_:.>\-()]+$/.test(s||'')?s:'body'}
  function addElement(kind){const d=frame();if(!d?.body)return;history();const tag=kind==='image'?'img':kind==='button'?'button':kind==='heading'?'h2':'div';const x=d.createElement(tag);x.className='ls-designer-created';x.dataset.lsDesigner='1';x.textContent=kind==='image'?'':kind==='button'?'BUTTON':kind==='heading'?'NEW HEADING':'NEW ELEMENT';if(kind==='image'){x.alt='Designer image';x.src='data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="640" height="360"%3E%3Crect width="100%" height="100%" fill="%230b1020"/%3E%3Ctext x="50%" y="50%" fill="%23ffd21a" text-anchor="middle" font-family="sans-serif" font-size="28"%3EIMAGE%3C/text%3E%3C/svg%3E'}x.style.cssText='position:absolute;left:50px;top:150px;width:240px;min-height:56px;padding:14px;box-sizing:border-box;background:#0b1020;color:#ffd21a;border:1px solid #ffd21a;z-index:9999;';d.body.append(x);apply();toast(`Added ${kind}`);}
  function align(mode){const x=el(),d=frame();if(!x||!d)return;history();const r=x.getBoundingClientRect(),vw=d.documentElement.clientWidth,vh=d.documentElement.clientHeight;let dx=0,dy=0;if(mode==='left')dx=-r.left;if(mode==='center')dx=(vw-r.width)/2-r.left;if(mode==='right')dx=vw-r.width-r.left;if(mode==='top')dy=-r.top;if(mode==='middle')dy=(vh-r.height)/2-r.top;if(mode==='bottom')dy=vh-r.height-r.top;move(dx,dy);toast('Aligned')}
  function saveLocal(){localStorage.setItem(KEY,JSON.stringify(plus.patches))}
  function loadLocal(){try{const p=JSON.parse(localStorage.getItem(KEY)||'null');if(p?.desktop)plus.patches=p;apply()}catch{}}
  function toast(t){const n=document.createElement('div');n.className='plus-toast';n.textContent=t;document.body.append(n);setTimeout(()=>n.remove(),1400)}
  function panel(){if($('#plusTools'))return;const p=document.createElement('aside');p.id='plusTools';p.innerHTML=`<div class="plus-title">QUICK TOOLS</div><div class="plus-group"><button data-a="add:heading">＋ HEADING</button><button data-a="add:button">＋ BUTTON</button><button data-a="add:image">＋ IMAGE</button><button data-a="add:box">＋ BOX</button></div><div class="plus-group"><button data-a="text">EDIT TEXT</button><button data-a="hide">HIDE</button><button data-a="dup">DUPLICATE</button></div><div class="plus-group"><span class="plus-label">NUDGE</span><div class="nudge"><button data-a="move:0:-10">↑</button><button data-a="move:-10:0">←</button><button data-a="move:10:0">→</button><button data-a="move:0:10">↓</button></div></div><div class="plus-group"><span class="plus-label">ALIGN</span><div class="align"><button data-a="align:left">L</button><button data-a="align:center">C</button><button data-a="align:right">R</button><button data-a="align:top">T</button><button data-a="align:middle">M</button><button data-a="align:bottom">B</button></div></div><div class="plus-group"><label>TEXT COLOR<input id="plusColor" type="color" value="#ffd21a"></label><label>OPACITY<input id="plusOpacity" type="range" min="0" max="1" step=".01" value="1"></label><label>RADIUS<input id="plusRadius" type="range" min="0" max="80" value="0"></label></div><div class="plus-hint">Click an element, then use these tools. Arrow keys nudge. Shift = 10×.</div>`;document.body.append(p);p.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(!b)return;const [a,...v]=b.dataset.a.split(':');if(a==='add')addElement(v[0]);if(a==='text')editText();if(a==='hide')remove();if(a==='dup')duplicate();if(a==='move')move(+v[0],+v[1]);if(a==='align')align(v[0])});$('#plusColor').oninput=e=>change('color',e.target.value);$('#plusOpacity').oninput=e=>change('opacity',e.target.value);$('#plusRadius').oninput=e=>change('border-radius',e.target.value+'px')}
  function init(){panel();loadLocal();document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(!selected())return;const n=e.shiftKey?10:1;if(e.key==='ArrowUp'){e.preventDefault();move(0,-n)}if(e.key==='ArrowDown'){e.preventDefault();move(0,n)}if(e.key==='ArrowLeft'){e.preventDefault();move(-n,0)}if(e.key==='ArrowRight'){e.preventDefault();move(n,0)}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate()}});const f=$('#pageFrame');f?.addEventListener('load',()=>{setTimeout(()=>{apply();},50)});setTimeout(()=>{apply();},500)}
  window.LSDesignerPlus={version:1,addElement,move,align,saveLocal,loadLocal};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
