(()=>{
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const escapeHtml=s=>String(s??'').replace(/[&<>\"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[ch]));
const safeHref=e=>{const href=String(e?.href||'');return href==='/Suno'||href.startsWith('/Suno/')?href:'/Suno/Suno_Guide.html';};
const legacyRoutes={
  '/suno':'/Suno/Suno_Guide.html','/suno/complete':'/Suno/complete/complete-guide.html','/suno/command-center':'/Suno/command-center.html','/suno/prompt-architect':'/Suno/prompt-architect.html','/suno/style-builder':'/Suno/style-builder.html','/suno/lyrics-builder':'/Suno/lyrics-builder.html','/suno/controls':'/Suno/controls.html','/suno/troubleshooter':'/Suno/troubleshooter.html','/suno/workflow':'/Suno/workflow.html',
  '/suno/v6':'/Suno/guides/v6.html','/suno/prompting':'/Suno/guides/prompting.html','/suno/lyrics':'/Suno/guides/lyrics.html','/suno/styles':'/Suno/guides/styles.html','/suno/sliders':'/Suno/guides/sliders.html','/suno/voices':'/Suno/guides/voices.html','/suno/editing':'/Suno/guides/editing.html','/suno/audio':'/Suno/guides/audio.html','/suno/stems':'/Suno/guides/stems.html','/suno/studio':'/Suno/guides/studio.html','/suno/midi':'/Suno/guides/midi.html','/suno/effects':'/Suno/guides/effects.html','/suno/automation':'/Suno/guides/automation.html','/suno/production':'/Suno/guides/production.html','/suno/troubleshooting':'/Suno/guides/troubleshooting.html','/suno/rights':'/Suno/guides/rights.html',
  '/suno/deep-dives/ultimate-control':'/Suno/deep-dives/ultimate-control.html','/suno/deep-dives/everything-expansion':'/Suno/deep-dives/everything-expansion.html','/suno/deep-dives/final-current-expansion':'/Suno/deep-dives/final-current-expansion.html','/suno/deep-dives/coverage-audit':'/Suno/deep-dives/coverage-audit.html','/suno/deep-dives/gaps-closure':'/Suno/deep-dives/gaps-closure.html','/suno/deep-dives/gap-closure-all-remaining':'/Suno/deep-dives/gap-closure-all-remaining.html','/suno/deep-dives/additional-current-details':'/Suno/deep-dives/additional-current-details.html'
};
const topics=[['V6 FUNDAMENTALS','/Suno/guides/v6.html'],['PROMPT ENGINEERING','/Suno/guides/prompting.html'],['LYRICS ENGINEERING','/Suno/guides/lyrics.html'],['STYLE CONSTRUCTION','/Suno/guides/styles.html'],['CREATIVE CONTROLS','/Suno/guides/sliders.html'],['VOICES & IDENTITY','/Suno/guides/voices.html'],['SURGICAL EDITING','/Suno/guides/editing.html'],['AUDIO & REFERENCES','/Suno/guides/audio.html'],['STEMS & REMASTER','/Suno/guides/stems.html'],['STUDIO 2.0','/Suno/guides/studio.html'],['MIDI & WAVETABLE','/Suno/guides/midi.html'],['EFFECTS & PLUGINS','/Suno/guides/effects.html'],['AUTOMATION','/Suno/guides/automation.html'],['PRODUCTION SYSTEM','/Suno/guides/production.html'],['DIAGNOSTICS','/Suno/guides/troubleshooting.html'],['RIGHTS & RELEASE','/Suno/guides/rights.html']];
const deep=[['ULTIMATE CONTROL','/Suno/deep-dives/ultimate-control.html'],['EVERYTHING EXPANSION','/Suno/deep-dives/everything-expansion.html'],['FINAL CURRENT EXPANSION','/Suno/deep-dives/final-current-expansion.html'],['COVERAGE AUDIT','/Suno/deep-dives/coverage-audit.html'],['GAPS CLOSURE','/Suno/deep-dives/gaps-closure.html'],['ALL REMAINING CURRENT','/Suno/deep-dives/gap-closure-all-remaining.html'],['ADDITIONAL CURRENT DETAILS','/Suno/deep-dives/additional-current-details.html']];
const links=items=>items.map(([label,href])=>`<a href="${href}">${label}</a>`).join('');
const header=$('.site-header');
const navHTML=`<div class="header-inner"><a class="brand" href="/Suno/Suno_Guide.html" aria-label="LIL SYNN Suno V6 Guide home"><span>LIL SYNN</span><b>SUNO V6</b></a><nav class="site-nav" id="site-nav" aria-label="Guide navigation"><div class="nav-group"><button class="nav-trigger" type="button" aria-expanded="false" aria-controls="reader-create">CREATE <span>⌄</span></button><div class="nav-menu" id="reader-create">${links(topics.slice(0,4).concat(topics.slice(7,8)))}</div></div><div class="nav-group"><button class="nav-trigger" type="button" aria-expanded="false" aria-controls="reader-control">CONTROL <span>⌄</span></button><div class="nav-menu" id="reader-control">${links(topics.slice(4,7))}</div></div><div class="nav-group"><button class="nav-trigger" type="button" aria-expanded="false" aria-controls="reader-produce">PRODUCE <span>⌄</span></button><div class="nav-menu" id="reader-produce">${links(topics.slice(8))}</div></div><div class="nav-group"><button class="nav-trigger" type="button" aria-expanded="false" aria-controls="reader-research">RESEARCH <span>⌄</span></button><div class="nav-menu" id="reader-research">${links(deep)}</div></div><a class="nav-complete" href="/Suno/complete/complete-guide.html">COMPLETE GUIDE</a></nav><button class="nav-toggle" type="button" aria-expanded="false" aria-controls="site-nav" aria-label="Open guide navigation"><span></span><span></span><span></span><b>MENU</b></button></div>`;
if(header&&!header.querySelector('.header-inner'))header.innerHTML=navHTML;
const canonical=/^https?:\/\/(?:www\.)?github\.com\/LILSYNNOFFICIAL\/LIL-SYNN-s-Complete-Suno-V6-Guide/i;
const rawCanonical=/^https?:\/\/raw\.githubusercontent\.com\/LILSYNNOFFICIAL\/LIL-SYNN-s-Complete-Suno-V6-Guide/i;
$$('a').forEach(a=>{
  const raw=a.getAttribute('href')||'';
  if(legacyRoutes[raw])a.href=legacyRoutes[raw];
  if(canonical.test(a.href)||rawCanonical.test(a.href)){a.target='_blank';a.rel='noopener noreferrer';}
});
const normalize=p=>{const path=(p||'/').replace(/\/+$/,'')||'/';return path.toLowerCase();};
const current=normalize(location.pathname);
$$('.nav-menu a,.nav-complete').forEach(a=>{if(normalize(a.getAttribute('href'))===current){a.setAttribute('aria-current','page');a.closest('.nav-group')?.classList.add('active');}});
const nav=$('.nav-toggle'),menu=$('#site-nav');
function closeGroups(except=null){$$('.nav-group').forEach(g=>{if(g!==except)g.classList.remove('open');const b=$('.nav-trigger',g);if(b)b.setAttribute('aria-expanded',String(g===except&&g.classList.contains('open')));});}
$$('.nav-trigger').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();const group=btn.closest('.nav-group');const open=group.classList.toggle('open');closeGroups(open?group:null);btn.setAttribute('aria-expanded',String(open));}));
if(nav&&menu)nav.addEventListener('click',e=>{if(e.target.closest('.nav-trigger'))return;const open=menu.classList.toggle('open');nav.setAttribute('aria-expanded',String(open));nav.setAttribute('aria-label',open?'Close guide navigation':'Open guide navigation');if(!open)closeGroups();});
document.addEventListener('click',e=>{if(!e.target.closest('.nav-group')&&!e.target.closest('.nav-toggle'))closeGroups();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeGroups();menu?.classList.remove('open');nav?.setAttribute('aria-expanded','false');nav?.setAttribute('aria-label','Open guide navigation');}});
$$('.nav-menu a,.nav-complete').forEach(a=>a.addEventListener('click',()=>{closeGroups();menu?.classList.remove('open');nav?.setAttribute('aria-expanded','false');nav?.setAttribute('aria-label','Open guide navigation');}));
const input=$('#guide-search'),cards=$$('.guide-card'),chips=$$('.filter-chip');let filter='all';
function apply(){const q=(input?.value||'').trim().toLowerCase();let shown=0;cards.forEach(card=>{const okFilter=filter==='all'||card.dataset.category===filter;const hay=((card.dataset.search||'')+' '+card.textContent).toLowerCase();const show=okFilter&&(!q||hay.includes(q));card.hidden=!show;if(show)shown++;});const empty=$('#no-results');if(empty)empty.hidden=shown!==0;if(input)input.setAttribute('aria-label',`Search guide library${q?`, ${shown} results`:''}`);}
if(input){input.setAttribute('role','searchbox');input.addEventListener('input',apply);}chips.forEach(chip=>chip.addEventListener('click',()=>{chips.forEach(x=>x.classList.remove('active'));chip.classList.add('active');filter=chip.dataset.filter||'all';apply();}));
$$('.accordion-trigger').forEach(btn=>btn.addEventListener('click',()=>{const panel=document.getElementById(btn.getAttribute('aria-controls'));const open=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!open));if(panel)panel.hidden=open;}));
const top=$('.back-to-top');if(top)top.addEventListener('click',()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}));
function injectDonation(){
  $$('.site-footer').forEach(footer=>{
    if(footer.querySelector('.suno-donate'))return;
    const donate=document.createElement('a');
    donate.className='suno-donate';
    donate.href='https://cash.app/$lilsynnofficial';
    donate.target='_blank';
    donate.rel='noopener noreferrer';
    donate.setAttribute('aria-label','Donate to support Suno guide servers and development');
    donate.textContent='DONATE · SUPPORT THE SERVERS & DEVELOPMENT ↗';
    donate.style.cssText='display:inline-flex;align-items:center;justify-content:center;min-height:40px;padding:0 16px;border:1px solid rgba(201,154,62,.5);background:linear-gradient(135deg,rgba(201,154,62,.16),rgba(201,154,62,.05));color:#f1cf78!important;font-size:8px;font-weight:900;letter-spacing:.14em;white-space:nowrap;transition:.2s;text-decoration:none';
    donate.addEventListener('mouseenter',()=>{donate.style.background='linear-gradient(135deg,#f0cc73,#b9842e)';donate.style.color='#0b0906';});
    donate.addEventListener('mouseleave',()=>{donate.style.background='linear-gradient(135deg,rgba(201,154,62,.16),rgba(201,154,62,.05))';donate.style.color='#f1cf78';});
    footer.appendChild(donate);
  });
}
injectDonation();
let searchIndex=null;
const searchBoxStyles='position:fixed;inset:0;z-index:9999;background:rgba(5,5,4,.92);backdrop-filter:blur(12px);display:flex;align-items:flex-start;justify-content:center;padding:10vh 18px 30px;overflow:auto;';
function openGlobalResults(query){if(!query||!searchIndex)return;const q=query.trim().toLowerCase();if(q.length<2)return;let overlay=$('#global-search-results');if(!overlay){overlay=document.createElement('div');overlay.id='global-search-results';overlay.style.cssText=searchBoxStyles;document.body.appendChild(overlay);overlay.addEventListener('click',e=>{if(e.target===overlay)overlay.remove();});}const matches=searchIndex.entries.map(e=>{const hay=(e.title+' '+e.kicker+' '+e.text).toLowerCase();let score=0;if(hay.includes(q))score+=2;if(e.title.toLowerCase().includes(q))score+=8;return {...e,score};}).filter(e=>e.score).sort((a,b)=>b.score-a.score).slice(0,24);overlay.innerHTML=`<div style="width:min(980px,100%);border:1px solid rgba(201,154,62,.24);background:#0b0a08;box-shadow:0 24px 80px rgba(0,0,0,.55)"><div style="display:flex;justify-content:space-between;gap:20px;padding:18px 20px;border-bottom:1px solid rgba(201,154,62,.12)"><div><div style="color:#c99a3e;font-size:9px;font-weight:900;letter-spacing:.18em">GLOBAL GUIDE SEARCH</div><div style="color:#80786d;font-size:11px;margin-top:5px">${escapeHtml(matches.length)} result${matches.length===1?'':'s'} for “${escapeHtml(q)}”</div></div><button id="global-search-close" type="button" style="background:none;border:0;color:#c99a3e;font-size:20px;cursor:pointer">×</button></div><div style="padding:10px">${matches.length?matches.map(e=>`<a href="${escapeHtml(safeHref(e))}" style="display:block;padding:15px 14px;text-decoration:none;border-bottom:1px solid rgba(201,154,62,.08)"><div style="color:#c99a3e;font-size:8px;letter-spacing:.16em;font-weight:900">${escapeHtml(e.kicker)}</div><div style="color:#eee9df;font:400 23px Georgia,serif;margin:5px 0">${escapeHtml(e.title)}</div><div style="color:#81796e;font-size:12px;line-height:1.55">${escapeHtml(e.text.slice(Math.max(0,e.text.toLowerCase().indexOf(q)-90),Math.max(0,e.text.toLowerCase().indexOf(q)-90)+260))}</div></a>`).join(''):`<div style="padding:35px;color:#80786d;text-align:center">No matching content was found across the indexed guide.</div>`}</div></div>`;$('#global-search-close')?.addEventListener('click',()=>overlay.remove());}
fetch('/Suno/search-index.json',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(data=>{searchIndex=data;}).catch(()=>{});
if(input){let timer;input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>openGlobalResults(input.value),260);});input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();openGlobalResults(input.value);}});}
function injectLivePanel(){fetch('/Suno/manifest.json',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(m=>{if(!m||$('#suno-live-panel'))return;const anchor=$('.source-status')||$('.hero');if(!anchor)return;const panel=document.createElement('section');panel.id='suno-live-panel';panel.className='section';panel.style.cssText='border-top:1px solid rgba(201,154,62,.14);border-bottom:1px solid rgba(201,154,62,.14);display:grid;grid-template-columns:1fr 1fr;gap:40px;';panel.innerHTML=`<div><p class="eyebrow">WHAT’S NEW / LIVE BUILD</p><h2 style="margin:0;font:400 clamp(36px,4.5vw,58px)/.98 Georgia,serif">Fresh from the <em>source.</em></h2><p style="color:#8f877b;max-width:680px">This isolated build contains ${escapeHtml(m.coreTopics)} core topics, ${escapeHtml(m.deepDives)} research deep dives and ${escapeHtml(m.completeDocuments)} master complete-guide document.</p></div><div style="border-left:1px solid rgba(201,154,62,.14);padding-left:30px;align-self:center"><div style="color:#c99a3e;font-size:8px;font-weight:900;letter-spacing:.16em">LATEST SYNCHRONIZATION</div><div style="color:#eee9df;font:400 28px Georgia,serif;margin:8px 0">${escapeHtml(m.syncDate)}</div><div style="color:#71695f;font-size:11px">Search spans the core guides, research pages and creator tools.</div></div>`;anchor.insertAdjacentElement('afterend',panel);}).catch(()=>{});}
injectLivePanel();
})();
