(()=>{
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const topics=[['V6 FUNDAMENTALS','/suno/v6'],['PROMPT ENGINEERING','/suno/prompting'],['LYRICS ENGINEERING','/suno/lyrics'],['STYLE CONSTRUCTION','/suno/styles'],['CREATIVE CONTROLS','/suno/sliders'],['VOICES & IDENTITY','/suno/voices'],['SURGICAL EDITING','/suno/editing'],['AUDIO & REFERENCES','/suno/audio'],['STEMS & REMASTER','/suno/stems'],['STUDIO 2.0','/suno/studio'],['MIDI & WAVETABLE','/suno/midi'],['EFFECTS & PLUGINS','/suno/effects'],['AUTOMATION','/suno/automation'],['PRODUCTION SYSTEM','/suno/production'],['DIAGNOSTICS','/suno/troubleshooting'],['RIGHTS & RELEASE','/suno/rights']];
const deep=[['ULTIMATE CONTROL','/suno/deep-dives/ultimate-control'],['EVERYTHING EXPANSION','/suno/deep-dives/everything-expansion'],['FINAL CURRENT EXPANSION','/suno/deep-dives/final-current-expansion'],['COVERAGE AUDIT','/suno/deep-dives/coverage-audit'],['GAPS CLOSURE','/suno/deep-dives/gaps-closure'],['ALL REMAINING CURRENT','/suno/deep-dives/gap-closure-all-remaining'],['ADDITIONAL CURRENT DETAILS','/suno/deep-dives/additional-current-details']];
const links=items=>items.map(([label,href])=>`<a href="${href}">${label}</a>`).join('');
const navHTML=`<div class="header-inner"><a class="brand" href="/suno" aria-label="LIL SYNN Suno V6 Guide home"><span>LIL SYNN</span><b>SUNO V6</b></a><nav class="site-nav" id="site-nav" aria-label="Guide navigation"><div class="nav-group"><button class="nav-trigger" type="button" aria-expanded="false" aria-controls="reader-create">CREATE <span>⌄</span></button><div class="nav-menu" id="reader-create">${links(topics.slice(0,4).concat(topics.slice(7,8)))}</div></div><div class="nav-group"><button class="nav-trigger" type="button" aria-expanded="false" aria-controls="reader-control">CONTROL <span>⌄</span></button><div class="nav-menu" id="reader-control">${links(topics.slice(4,7))}</div></div><div class="nav-group"><button class="nav-trigger" type="button" aria-expanded="false" aria-controls="reader-produce">PRODUCE <span>⌄</span></button><div class="nav-menu" id="reader-produce">${links(topics.slice(8))}</div></div><div class="nav-group"><button class="nav-trigger" type="button" aria-expanded="false" aria-controls="reader-research">RESEARCH <span>⌄</span></button><div class="nav-menu" id="reader-research">${links(deep)}</div></div><a class="nav-complete" href="/suno/complete">COMPLETE GUIDE</a></nav><button class="nav-toggle" type="button" aria-expanded="false" aria-controls="site-nav"><span></span><span></span><span></span><b>MENU</b></button></div>`;
const header=$('.site-header');
if(header&&!header.querySelector('.header-inner'))header.innerHTML=navHTML;
$$('a[href*="github.com/LILSYNNOFFICIAL/LIL-SYNN-s-Complete-Suno-V6-Guide"],a[href*="raw.githubusercontent.com/LILSYNNOFFICIAL/LIL-SYNN-s-Complete-Suno-V6-Guide"]').forEach(a=>{a.href='/suno';a.removeAttribute('target');a.removeAttribute('rel');if(!a.textContent.trim())a.textContent='SUNO GUIDE';});
const nav=$('.nav-toggle'),menu=$('#site-nav');
function closeGroups(except=null){$$('.nav-group').forEach(g=>{if(g!==except)g.classList.remove('open');const b=$('.nav-trigger',g);if(b)b.setAttribute('aria-expanded',String(g===except&&g.classList.contains('open')));});}
$$('.nav-trigger').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();const group=btn.closest('.nav-group');const open=group.classList.toggle('open');closeGroups(open?group:null);btn.setAttribute('aria-expanded',String(open));}));
if(nav&&menu)nav.addEventListener('click',()=>{const open=menu.classList.toggle('open');nav.setAttribute('aria-expanded',String(open));if(!open)closeGroups();});
document.addEventListener('click',e=>{if(!e.target.closest('.nav-group'))closeGroups();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeGroups();menu?.classList.remove('open');nav?.setAttribute('aria-expanded','false');}});
$$('.nav-menu a,.nav-complete').forEach(a=>a.addEventListener('click',()=>{closeGroups();menu?.classList.remove('open');nav?.setAttribute('aria-expanded','false');}));
const input=$('#guide-search'),cards=$$('.guide-card'),chips=$$('.filter-chip');let filter='all';
function apply(){const q=(input?.value||'').trim().toLowerCase();let shown=0;cards.forEach(card=>{const okFilter=filter==='all'||card.dataset.category===filter;const hay=((card.dataset.search||'')+' '+card.textContent).toLowerCase();const show=okFilter&&(!q||hay.includes(q));card.hidden=!show;if(show)shown++;});const empty=$('#no-results');if(empty)empty.hidden=shown!==0;}
if(input)input.addEventListener('input',apply);chips.forEach(chip=>chip.addEventListener('click',()=>{chips.forEach(x=>x.classList.remove('active'));chip.classList.add('active');filter=chip.dataset.filter||'all';apply();}));
$$('.accordion-trigger').forEach(btn=>btn.addEventListener('click',()=>{const panel=document.getElementById(btn.getAttribute('aria-controls'));const open=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!open));if(panel)panel.hidden=open;}));
const top=$('.back-to-top');if(top)top.addEventListener('click',()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}));
})();