const crypto=require('node:crypto');
const REPO='LILSYNNOFFICIAL/LILSYNNOFFICIAL';
const COOKIE='ls_admin_session';
const RATE=new Map();

function env(name){return process.env[name]||''}
function json(res,status,payload){res.status(status).setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(payload));}
function b64(v){return Buffer.from(v).toString('base64url')}
function unb64(v){return Buffer.from(v,'base64url').toString('utf8')}
function sign(v){return crypto.createHmac('sha256',env('ADMIN_SESSION_SECRET')).update(v).digest('base64url')}
function sessionToken(email,ttl=60*60*8){const body=b64(JSON.stringify({email,exp:Date.now()+ttl*1000,nonce:crypto.randomBytes(12).toString('hex')}));return body+'.'+sign(body)}
function validSession(req){const raw=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(COOKIE+'='));if(!raw)return null;const token=decodeURIComponent(raw.slice(COOKIE.length+1));const [body,sig]=token.split('.');if(!body||!sig||!env('ADMIN_SESSION_SECRET'))return null;const expected=sign(body);if(!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;try{const p=JSON.parse(unb64(body));return p.exp>Date.now()?p:null}catch{return null}}
function requireAdmin(req,res){const s=validSession(req);if(!s){json(res,401,{ok:false,error:'AUTH_REQUIRED'});return null}return s}
function verifyPassword(password){const stored=env('ADMIN_PASSWORD_HASH');if(!stored||!password)return false;const [scheme,saltHex,keyHex]=stored.split('$');if(scheme!=='scrypt'||!saltHex||!keyHex)return false;try{const actual=crypto.scryptSync(password,Buffer.from(saltHex,'hex'),64,{N:16384,r:8,p:1});const expected=Buffer.from(keyHex,'hex');return expected.length===actual.length&&crypto.timingSafeEqual(actual,expected)}catch{return false}}
function rateOk(ip){const now=Date.now(),a=RATE.get(ip)||[];const recent=a.filter(t=>now-t<15*60*1000);if(recent.length>=10){RATE.set(ip,recent);return false}recent.push(now);RATE.set(ip,recent);return true}
async function gh(path,opts={}){const token=env('GITHUB_TOKEN');if(!token)throw new Error('GITHUB_TOKEN is not configured');const r=await fetch('https://api.github.com/repos/'+REPO+path,{...opts,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:'Bearer '+token,'Content-Type':'application/json',...(opts.headers||{})}});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={message:text}}if(!r.ok)throw new Error(`GitHub ${r.status}: ${data.message||'request failed'}`);return data}
async function vercel(path,opts={}){const token=env('VERCEL_TOKEN');if(!token)throw new Error('VERCEL_TOKEN is not configured');const r=await fetch('https://api.vercel.com'+path,{...opts,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(opts.headers||{})}});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={message:text}}if(!r.ok)throw new Error(`Vercel ${r.status}: ${data.error?.message||data.message||'request failed'}`);return data}
async function kv(action,key,value){const u=env('AUDIT_KV_URL'),t=env('AUDIT_KV_TOKEN');if(!u||!t)return false;const r=await fetch(u,{method:'POST',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify(action==='push'?['LPUSH',key,value]:['LRANGE',key,0,199])});return r.ok}
async function audit(event){try{await kv('push','ls-admin-audit',JSON.stringify({...event,at:new Date().toISOString()}))}catch{} }
async function body(req){if(req.body!==undefined&&req.body!==null){if(typeof req.body==='string')try{return JSON.parse(req.body)}catch{return {raw:req.body}};return req.body}return await new Promise((resolve,reject)=>{let d=[];req.on('data',c=>d.push(c));req.on('end',()=>{const s=Buffer.concat(d).toString('utf8');try{resolve(s?JSON.parse(s):{})}catch{resolve({})}});req.on('error',reject)})}
function confirmGate(payload,required){if(payload.confirmation!==required)return false;return true}

module.exports=async function handler(req,res){
  const action=String(req.query?.action||'session');
  const ip=(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0].trim();
  try{
    if(action==='login'&&req.method==='POST'){
      if(!rateOk(ip))return json(res,429,{ok:false,error:'TOO_MANY_ATTEMPTS'});
      const p=await body(req);const email=String(p.email||'').trim().toLowerCase();
      if(email!==String(env('ADMIN_EMAIL')).trim().toLowerCase()||!verifyPassword(String(p.password||'')))return json(res,401,{ok:false,error:'INVALID_CREDENTIALS'});
      res.setHeader('Set-Cookie',`${COOKIE}=${encodeURIComponent(sessionToken(email))}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=28800`);await audit({action:'login',ip});return json(res,200,{ok:true,email});
    }
    if(action==='logout'&&req.method==='POST'){res.setHeader('Set-Cookie',`${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`);await audit({action:'logout',ip});return json(res,200,{ok:true})}
    const admin=requireAdmin(req,res);if(!admin)return;
    if(action==='session')return json(res,200,{ok:true,email:admin.email,expiresAt:admin.exp});
    if(action==='dashboard'&&req.method==='GET'){
      const [repo,runs,commits]=await Promise.all([gh(''),gh('/actions/runs?per_page=8'),gh('/commits?sha=main&per_page=8')]);
      let deployments=null;try{deployments=await vercel(`/v6/deployments?projectId=${encodeURIComponent(env('VERCEL_PROJECT_ID'))}&teamId=${encodeURIComponent(env('VERCEL_TEAM_ID'))}&limit=8`)}catch(e){deployments={error:e.message}}
      return json(res,200,{ok:true,repo,runs:runs.workflow_runs,commits,deployments});
    }
    if(action==='commits'&&req.method==='GET')return json(res,200,{ok:true,commits:await gh('/commits?sha=main&per_page=50')});
    if(action==='deployments'&&req.method==='GET')return json(res,200,{ok:true,deployments:await vercel(`/v6/deployments?projectId=${encodeURIComponent(env('VERCEL_PROJECT_ID'))}&teamId=${encodeURIComponent(env('VERCEL_TEAM_ID'))}&limit=30`)});
    if(action==='audit'&&req.method==='GET'){const u=env('AUDIT_KV_URL'),t=env('AUDIT_KV_TOKEN');if(!u||!t)return json(res,200,{ok:true,configured:false,events:[]});const r=await fetch(u,{method:'POST',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify(['LRANGE','ls-admin-audit',0,199])});const d=await r.json();return json(res,200,{ok:true,configured:true,events:(d.result||[]).map(x=>{try{return JSON.parse(x)}catch{return {raw:x}}})})}
    if(action==='visual-qa'&&req.method==='POST'){const p=await body(req);if(p.confirmation!=='RUN VISUAL QA')return json(res,400,{ok:false,error:'CONFIRMATION_REQUIRED'});const result=await gh('/actions/workflows/admin-visual-qa.yml/dispatches',{method:'POST',body:JSON.stringify({ref:'main',inputs:{actor:admin.email,route:String(p.route||'/index2'),viewport:String(p.viewport||'desktop')}})});await audit({action:'visual-qa',route:p.route,viewport:p.viewport});return json(res,202,{ok:true,queued:true,result});}
    if(action==='revert'&&req.method==='POST'){const p=await body(req);if(!confirmGate(p,'REVERT COMMIT'))return json(res,400,{ok:false,error:'CONFIRMATION_REQUIRED'});if(!/^[0-9a-f]{40}$/i.test(String(p.sha||'')))return json(res,400,{ok:false,error:'INVALID_SHA'});await gh('/actions/workflows/admin-git.yml/dispatches',{method:'POST',body:JSON.stringify({ref:'main',inputs:{operation:'revert',target_sha:p.sha,branch:'main',actor:admin.email}})});await audit({action:'revert',sha:p.sha});return json(res,202,{ok:true,queued:true})}
    if(action==='restore'&&req.method==='POST'){const p=await body(req);if(p.confirmation1!=='ROLL BACK HISTORY'||p.confirmation2!=='YES, REWRITE HISTORY')return json(res,400,{ok:false,error:'DOUBLE_CONFIRMATION_REQUIRED'});if(!/^[0-9a-f]{40}$/i.test(String(p.sha||'')))return json(res,400,{ok:false,error:'INVALID_SHA'});if(!verifyPassword(String(p.password||'')))return json(res,403,{ok:false,error:'REAUTH_REQUIRED'});await gh('/actions/workflows/admin-git.yml/dispatches',{method:'POST',body:JSON.stringify({ref:'main',inputs:{operation:'restore',target_sha:p.sha,branch:'main',actor:admin.email}})});await audit({action:'history-rewrite',sha:p.sha});return json(res,202,{ok:true,queued:true})}
    if(action==='rollback-deployment'&&req.method==='POST'){const p=await body(req);if(p.confirmation1!=='ROLL BACK DEPLOYMENT'||p.confirmation2!=='YES, SWITCH PRODUCTION')return json(res,400,{ok:false,error:'DOUBLE_CONFIRMATION_REQUIRED'});if(!verifyPassword(String(p.password||'')))return json(res,403,{ok:false,error:'REAUTH_REQUIRED'});const project=env('VERCEL_PROJECT_ID'),team=env('VERCEL_TEAM_ID');await vercel(`/v1/projects/${encodeURIComponent(project)}/rollback/${encodeURIComponent(p.deploymentId)}?teamId=${encodeURIComponent(team)}`,{method:'POST',body:'{}'});await audit({action:'deployment-rollback',deploymentId:p.deploymentId});return json(res,200,{ok:true})}
    if(action==='promote-deployment'&&req.method==='POST'){const p=await body(req);if(p.confirmation!=='PROMOTE DEPLOYMENT')return json(res,400,{ok:false,error:'CONFIRMATION_REQUIRED'});await vercel(`/v10/projects/${encodeURIComponent(env('VERCEL_PROJECT_ID'))}/promote/${encodeURIComponent(p.deploymentId)}?teamId=${encodeURIComponent(env('VERCEL_TEAM_ID'))}`,{method:'POST',body:'{}'});await audit({action:'deployment-promote',deploymentId:p.deploymentId});return json(res,200,{ok:true})}
    if(action==='delete-deployment'&&req.method==='POST'){const p=await body(req);if(p.confirmation1!=='DELETE DEPLOYMENT'||p.confirmation2!=='YES, DELETE IT')return json(res,400,{ok:false,error:'DOUBLE_CONFIRMATION_REQUIRED'});if(!verifyPassword(String(p.password||'')))return json(res,403,{ok:false,error:'REAUTH_REQUIRED'});await vercel(`/v13/deployments/${encodeURIComponent(p.deploymentId)}?teamId=${encodeURIComponent(env('VERCEL_TEAM_ID'))}`,{method:'DELETE'});await audit({action:'deployment-delete',deploymentId:p.deploymentId});return json(res,200,{ok:true})}
    if(action==='upload'&&req.method==='POST'){
      const p=await body(req);const files=Array.isArray(p.files)?p.files:[];if(!files.length)return json(res,400,{ok:false,error:'NO_FILES'});if(files.some(f=>!f.name||!f.data||f.data.length>5*1024*1024))return json(res,413,{ok:false,error:'FILE_TOO_LARGE_OR_INVALID'});const out=[];for(const f of files){const safe=String(f.name).replace(/\\/g,'/').split('/').pop().replace(/[^a-zA-Z0-9._ -]/g,'_');if(!safe||safe==='.'||safe==='..')continue;const path='assets/img/'+safe;let sha=null;try{sha=(await gh('/contents/'+encodeURIComponent(path))).sha}catch{}const payload={message:`admin: upload asset ${safe}`,content:String(f.data).replace(/^data:[^;]+;base64,/,'')};if(sha)payload.sha=sha;const r=await gh('/contents/'+encodeURIComponent(path),{method:'PUT',body:JSON.stringify(payload)});out.push({name:safe,path,sha:r.content?.sha})}await audit({action:'upload',count:out.length,files:out.map(x=>x.path)});return json(res,200,{ok:true,files:out})}
    if(action==='delete-file'&&req.method==='POST'){const p=await body(req);if(p.confirmation!=='DELETE ASSET')return json(res,400,{ok:false,error:'CONFIRMATION_REQUIRED'});const filePath=String(p.path||'');if(!/^assets\/img\/[A-Za-z0-9._ -]+$/.test(filePath))return json(res,400,{ok:false,error:'INVALID_ASSET_PATH'});const current=await gh('/contents/'+encodeURIComponent(filePath));await gh('/contents/'+encodeURIComponent(filePath),{method:'DELETE',body:JSON.stringify({message:`admin: delete asset ${filePath.split('/').pop()}`,sha:current.sha})});await audit({action:'delete-file',path:filePath});return json(res,200,{ok:true})}
    if(action==='env-status'&&req.method==='GET')return json(res,200,{ok:true,configured:{ADMIN_EMAIL:!!env('ADMIN_EMAIL'),ADMIN_PASSWORD_HASH:!!env('ADMIN_PASSWORD_HASH'),ADMIN_SESSION_SECRET:!!env('ADMIN_SESSION_SECRET'),GITHUB_TOKEN:!!env('GITHUB_TOKEN'),VERCEL_TOKEN:!!env('VERCEL_TOKEN'),VERCEL_PROJECT_ID:!!env('VERCEL_PROJECT_ID'),VERCEL_TEAM_ID:!!env('VERCEL_TEAM_ID'),AUDIT_KV_URL:!!env('AUDIT_KV_URL'),AUDIT_KV_TOKEN:!!env('AUDIT_KV_TOKEN')}});
    return json(res,404,{ok:false,error:'UNKNOWN_ACTION'});
  }catch(e){console.error('admin error',e);return json(res,500,{ok:false,error:'ADMIN_OPERATION_FAILED',detail:process.env.NODE_ENV==='development'?e.message:undefined})}
}
