const crypto=require('node:crypto');
const REPO='LILSYNNOFFICIAL/LILSYNNOFFICIAL';const COOKIE='ls_admin_session';
const SAFE_TAGS=new Set(['div','section','article','aside','header','footer','main','nav','p','span','h1','h2','h3','h4','h5','h6','a','img','video','button','strong','em','small','figure','figcaption','hr']);
const SAFE_ATTRS=new Set(['id','class','title','alt','href','src','target','rel','controls','autoplay','muted','loop','poster','type','aria-label','role']);
const SAFE_STYLE=new Set(['position','top','right','bottom','left','width','height','min-width','max-width','min-height','max-height','margin','padding','display','flex','flex-direction','flex-wrap','flex-grow','flex-shrink','flex-basis','justify-content','align-items','gap','font-family','font-size','font-weight','line-height','letter-spacing','text-align','text-transform','color','background','background-color','border','border-width','border-style','border-color','border-radius','box-shadow','opacity','z-index','overflow','object-fit']);
const SEL=/^#[A-Za-z][A-Za-z0-9_-]*$|^body(?:>[a-z][a-z0-9-]*(?::nth-of-type\([1-9][0-9]*\))?)*$/;
function env(n){return process.env[n]||''}function json(res,s,p){res.status(s).setHeader('Content-Type','application/json');res.end(JSON.stringify(p))}
function sign(v){return crypto.createHmac('sha256',env('ADMIN_SESSION_SECRET')).update(v).digest('base64url')}
function validSession(req){const raw=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(COOKIE+'='));if(!raw||!env('ADMIN_SESSION_SECRET'))return null;const [body,sig]=decodeURIComponent(raw.slice(COOKIE.length+1)).split('.');if(!body||!sig)return null;const expected=sign(body);if(sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;try{const p=JSON.parse(Buffer.from(body,'base64url').toString('utf8'));return p.exp>Date.now()?p:null}catch{return null}}
async function gh(path,opts={}){const token=env('GITHUB_TOKEN');if(!token)throw Error('GITHUB_TOKEN is not configured');const r=await fetch('https://api.github.com/repos/'+REPO+path,{...opts,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:'Bearer '+token,'Content-Type':'application/json',...(opts.headers||{})}});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={message:t}}if(!r.ok)throw Error(`GitHub ${r.status}: ${d.message||'request failed'}`);return d}
async function body(req){if(req.body!==undefined)return typeof req.body==='string'?JSON.parse(req.body):req.body;return await new Promise((resolve,reject)=>{let d=[];req.on('data',c=>d.push(c));req.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(d).toString('utf8')||'{}'))}catch(e){reject(e)}});req.on('error',reject)})}
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function safeUrl(v){return /^\/(?:assets\/|images\/|media\/)/.test(String(v||''))||/^https:\/\//.test(String(v||''))}
function validate(p){if(!p||!Array.isArray(p.created)||p.created.length>100||!Array.isArray(p.deleted)||p.deleted.length>100)throw Error('INVALID_DOM_PAYLOAD');if(p.confirmation!=='SAVE DOM')throw Error('CONFIRMATION_REQUIRED');if(p.baseSha&&!/^[0-9a-f]{40}$/i.test(String(p.baseSha)))throw Error('INVALID_BASE_SHA');for(const x of p.created){if(!/^[a-z0-9][a-z0-9_-]{0,63}$/i.test(String(x.id||''))||!SAFE_TAGS.has(String(x.tag||'').toLowerCase()))throw Error('INVALID_DOM_ELEMENT');if(x.text!=null&&String(x.text).length>10000)throw Error('DOM_TEXT_TOO_LARGE');for(const [k,v] of Object.entries(x.attrs||{})){if(!SAFE_ATTRS.has(k)||String(v).length>1000||/[<>`]/.test(String(v)))throw Error('INVALID_DOM_ATTRIBUTE');if(['src','href','poster'].includes(k)&&!safeUrl(v))throw Error('INVALID_DOM_URL')}for(const [k,v] of Object.entries(x.style||{})){if(!SAFE_STYLE.has(k)||String(v).length>240||/[{}<>`;]/.test(String(v))||/javascript\s*:/i.test(String(v)))throw Error('INVALID_DOM_STYLE')}}for(const s of p.deleted){if(typeof s!=='string'||s.length>260||!SEL.test(s))throw Error('INVALID_DOM_SELECTOR')}}
function elementHtml(x){const tag=String(x.tag).toLowerCase();const attrs=Object.entries(x.attrs||{}).filter(([k])=>SAFE_ATTRS.has(k)).map(([k,v])=>` ${k}="${esc(v)}"`).join('');const style=Object.entries(x.style||{}).filter(([k])=>SAFE_STYLE.has(k)).map(([k,v])=>`${k}:${String(v)}!important`).join(';');const sa=style?` style="${esc(style)}"`:'';const id=` data-ls-id="${esc(x.id)}" data-ls-designer="1"`;if(['img','hr'].includes(tag))return `<${tag}${id}${attrs}${sa}>`;return `<${tag}${id}${attrs}${sa}>${esc(x.text||'')}</${tag}>`}
function domBlock(a){return `<!-- LS-DESIGNER-DOM:START -->\n${a.map(elementHtml).join('\n')}\n<!-- LS-DESIGNER-DOM:END -->`}
function hideBlock(a){return `<!-- LS-DESIGNER-HIDE:START -->\n${a.map(s=>`${s}{display:none!important}`).join('\n')}\n<!-- LS-DESIGNER-HIDE:END -->`}
function replaceBlock(src,start,end,block,anchor){const a=src.indexOf(start),b=src.indexOf(end);if(a>=0&&b>a)return src.slice(0,a)+block+src.slice(b+end.length);const i=src.indexOf(anchor);if(i<0)throw Error('INDEX_BODY_ANCHOR_NOT_FOUND');return src.slice(0,i)+block+'\n'+src.slice(i)}
module.exports=async function handler(req,res){try{if(req.method!=='POST')return json(res,405,{ok:false,error:'METHOD_NOT_ALLOWED'});if(!validSession(req))return json(res,401,{ok:false,error:'AUTH_REQUIRED'});const p=await body(req);validate(p);const latest=(await gh('/commits?sha=main&per_page=1'))[0];if(p.baseSha&&latest?.sha&&String(p.baseSha)!==String(latest.sha))return json(res,409,{ok:false,error:'LAYOUT_CONFLICT',currentSha:latest.sha});const file=await gh('/contents/index.html');let html=Buffer.from(file.content,'base64').toString('utf8');html=replaceBlock(html,'<!-- LS-DESIGNER-DOM:START -->','<!-- LS-DESIGNER-DOM:END -->',domBlock(p.created),'</body>');if(p.deleted.length)html=replaceBlock(html,'<!-- LS-DESIGNER-HIDE:START -->','<!-- LS-DESIGNER-HIDE:END -->',hideBlock(p.deleted),'</head>');else{const a=html.indexOf('<!-- LS-DESIGNER-HIDE:START -->'),b=html.indexOf('<!-- LS-DESIGNER-HIDE:END -->');if(a>=0&&b>a)html=html.slice(0,a)+html.slice(b+'<!-- LS-DESIGNER-HIDE:END -->'.length)}const updated=await gh('/contents/index.html',{method:'PUT',body:JSON.stringify({message:`admin: save visual DOM (${p.created.length} elements)`,content:Buffer.from(html,'utf8').toString('base64'),sha:file.sha})});return json(res,200,{ok:true,sha:updated.commit?.sha||updated.content?.sha||''})}catch(e){return json(res,400,{ok:false,error:e.message||'SAVE_DOM_FAILED'})}};
